// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package warpmenuentry

import (
	"context"

	"github.com/cloudogu/cesapp-lib/core"
	"github.com/cloudogu/k8s-dogu-lib/v3/api/v2"
	"github.com/cloudogu/k8s-warp-menu-entry-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// EnsureWarpMenuEntry provides a mock function for the type MockManager
func (_mock *MockManager) EnsureWarpMenuEntry(ctx context.Context, doguResource *v2.Dogu) error {
	ret := _mock.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for EnsureWarpMenuEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.Dogu) error); ok {
		r0 = returnFunc(ctx, doguResource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_EnsureWarpMenuEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureWarpMenuEntry'
type MockManager_EnsureWarpMenuEntry_Call struct {
	*mock.Call
}

// EnsureWarpMenuEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *MockManager_Expecter) EnsureWarpMenuEntry(ctx any, doguResource any) *MockManager_EnsureWarpMenuEntry_Call {
	return &MockManager_EnsureWarpMenuEntry_Call{Call: _e.mock.On("EnsureWarpMenuEntry", ctx, doguResource)}
}

func (_c *MockManager_EnsureWarpMenuEntry_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *MockManager_EnsureWarpMenuEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.Dogu
		if args[1] != nil {
			arg1 = args[1].(*v2.Dogu)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_EnsureWarpMenuEntry_Call) Return(err error) *MockManager_EnsureWarpMenuEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_EnsureWarpMenuEntry_Call) RunAndReturn(run func(ctx context.Context, doguResource *v2.Dogu) error) *MockManager_EnsureWarpMenuEntry_Call {
	_c.Call.Return(run)
	return _c
}

// newMockLocalDoguFetcher creates a new instance of mockLocalDoguFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLocalDoguFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLocalDoguFetcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockLocalDoguFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockLocalDoguFetcher is an autogenerated mock type for the localDoguFetcher type
type mockLocalDoguFetcher struct {
	mock.Mock
}

type mockLocalDoguFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLocalDoguFetcher) EXPECT() *mockLocalDoguFetcher_Expecter {
	return &mockLocalDoguFetcher_Expecter{mock: &_m.Mock}
}

// FetchForResource provides a mock function for the type mockLocalDoguFetcher
func (_mock *mockLocalDoguFetcher) FetchForResource(ctx context.Context, doguResource *v2.Dogu) (*core.Dogu, error) {
	ret := _mock.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for FetchForResource")
	}

	var r0 *core.Dogu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.Dogu) (*core.Dogu, error)); ok {
		return returnFunc(ctx, doguResource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.Dogu) *core.Dogu); ok {
		r0 = returnFunc(ctx, doguResource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v2.Dogu) error); ok {
		r1 = returnFunc(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockLocalDoguFetcher_FetchForResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchForResource'
type mockLocalDoguFetcher_FetchForResource_Call struct {
	*mock.Call
}

// FetchForResource is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *mockLocalDoguFetcher_Expecter) FetchForResource(ctx any, doguResource any) *mockLocalDoguFetcher_FetchForResource_Call {
	return &mockLocalDoguFetcher_FetchForResource_Call{Call: _e.mock.On("FetchForResource", ctx, doguResource)}
}

func (_c *mockLocalDoguFetcher_FetchForResource_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *mockLocalDoguFetcher_FetchForResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.Dogu
		if args[1] != nil {
			arg1 = args[1].(*v2.Dogu)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockLocalDoguFetcher_FetchForResource_Call) Return(dogu *core.Dogu, err error) *mockLocalDoguFetcher_FetchForResource_Call {
	_c.Call.Return(dogu, err)
	return _c
}

func (_c *mockLocalDoguFetcher_FetchForResource_Call) RunAndReturn(run func(ctx context.Context, doguResource *v2.Dogu) (*core.Dogu, error)) *mockLocalDoguFetcher_FetchForResource_Call {
	_c.Call.Return(run)
	return _c
}

// newMockWarpmenuentryClient creates a new instance of mockWarpmenuentryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWarpmenuentryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWarpmenuentryClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockWarpmenuentryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockWarpmenuentryClient is an autogenerated mock type for the warpmenuentryClient type
type mockWarpmenuentryClient struct {
	mock.Mock
}

type mockWarpmenuentryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockWarpmenuentryClient) EXPECT() *mockWarpmenuentryClient_Expecter {
	return &mockWarpmenuentryClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockWarpmenuentryClient
func (_mock *mockWarpmenuentryClient) Create(ctx context.Context, warpMenuEntry *v1.WarpMenuEntry, opts v10.CreateOptions) (*v1.WarpMenuEntry, error) {
	ret := _mock.Called(ctx, warpMenuEntry, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.WarpMenuEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.WarpMenuEntry, v10.CreateOptions) (*v1.WarpMenuEntry, error)); ok {
		return returnFunc(ctx, warpMenuEntry, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.WarpMenuEntry, v10.CreateOptions) *v1.WarpMenuEntry); ok {
		r0 = returnFunc(ctx, warpMenuEntry, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.WarpMenuEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.WarpMenuEntry, v10.CreateOptions) error); ok {
		r1 = returnFunc(ctx, warpMenuEntry, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockWarpmenuentryClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockWarpmenuentryClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - warpMenuEntry *v1.WarpMenuEntry
//   - opts v10.CreateOptions
func (_e *mockWarpmenuentryClient_Expecter) Create(ctx any, warpMenuEntry any, opts any) *mockWarpmenuentryClient_Create_Call {
	return &mockWarpmenuentryClient_Create_Call{Call: _e.mock.On("Create", ctx, warpMenuEntry, opts)}
}

func (_c *mockWarpmenuentryClient_Create_Call) Run(run func(ctx context.Context, warpMenuEntry *v1.WarpMenuEntry, opts v10.CreateOptions)) *mockWarpmenuentryClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.WarpMenuEntry
		if args[1] != nil {
			arg1 = args[1].(*v1.WarpMenuEntry)
		}
		var arg2 v10.CreateOptions
		if args[2] != nil {
			arg2 = args[2].(v10.CreateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockWarpmenuentryClient_Create_Call) Return(warpMenuEntry1 *v1.WarpMenuEntry, err error) *mockWarpmenuentryClient_Create_Call {
	_c.Call.Return(warpMenuEntry1, err)
	return _c
}

func (_c *mockWarpmenuentryClient_Create_Call) RunAndReturn(run func(ctx context.Context, warpMenuEntry *v1.WarpMenuEntry, opts v10.CreateOptions) (*v1.WarpMenuEntry, error)) *mockWarpmenuentryClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockWarpmenuentryClient
func (_mock *mockWarpmenuentryClient) Delete(ctx context.Context, name string, opts v10.DeleteOptions) error {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v10.DeleteOptions) error); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockWarpmenuentryClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockWarpmenuentryClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v10.DeleteOptions
func (_e *mockWarpmenuentryClient_Expecter) Delete(ctx any, name any, opts any) *mockWarpmenuentryClient_Delete_Call {
	return &mockWarpmenuentryClient_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockWarpmenuentryClient_Delete_Call) Run(run func(ctx context.Context, name string, opts v10.DeleteOptions)) *mockWarpmenuentryClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v10.DeleteOptions
		if args[2] != nil {
			arg2 = args[2].(v10.DeleteOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockWarpmenuentryClient_Delete_Call) Return(err error) *mockWarpmenuentryClient_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockWarpmenuentryClient_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, opts v10.DeleteOptions) error) *mockWarpmenuentryClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mockWarpmenuentryClient
func (_mock *mockWarpmenuentryClient) Get(ctx context.Context, name string, opts v10.GetOptions) (*v1.WarpMenuEntry, error) {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.WarpMenuEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v10.GetOptions) (*v1.WarpMenuEntry, error)); ok {
		return returnFunc(ctx, name, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v10.GetOptions) *v1.WarpMenuEntry); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.WarpMenuEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, v10.GetOptions) error); ok {
		r1 = returnFunc(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockWarpmenuentryClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockWarpmenuentryClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v10.GetOptions
func (_e *mockWarpmenuentryClient_Expecter) Get(ctx any, name any, opts any) *mockWarpmenuentryClient_Get_Call {
	return &mockWarpmenuentryClient_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockWarpmenuentryClient_Get_Call) Run(run func(ctx context.Context, name string, opts v10.GetOptions)) *mockWarpmenuentryClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v10.GetOptions
		if args[2] != nil {
			arg2 = args[2].(v10.GetOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockWarpmenuentryClient_Get_Call) Return(warpMenuEntry *v1.WarpMenuEntry, err error) *mockWarpmenuentryClient_Get_Call {
	_c.Call.Return(warpMenuEntry, err)
	return _c
}

func (_c *mockWarpmenuentryClient_Get_Call) RunAndReturn(run func(ctx context.Context, name string, opts v10.GetOptions) (*v1.WarpMenuEntry, error)) *mockWarpmenuentryClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockWarpmenuentryClient
func (_mock *mockWarpmenuentryClient) Update(ctx context.Context, warpMenuEntry *v1.WarpMenuEntry, opts v10.UpdateOptions) (*v1.WarpMenuEntry, error) {
	ret := _mock.Called(ctx, warpMenuEntry, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.WarpMenuEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.WarpMenuEntry, v10.UpdateOptions) (*v1.WarpMenuEntry, error)); ok {
		return returnFunc(ctx, warpMenuEntry, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.WarpMenuEntry, v10.UpdateOptions) *v1.WarpMenuEntry); ok {
		r0 = returnFunc(ctx, warpMenuEntry, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.WarpMenuEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.WarpMenuEntry, v10.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, warpMenuEntry, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockWarpmenuentryClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockWarpmenuentryClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - warpMenuEntry *v1.WarpMenuEntry
//   - opts v10.UpdateOptions
func (_e *mockWarpmenuentryClient_Expecter) Update(ctx any, warpMenuEntry any, opts any) *mockWarpmenuentryClient_Update_Call {
	return &mockWarpmenuentryClient_Update_Call{Call: _e.mock.On("Update", ctx, warpMenuEntry, opts)}
}

func (_c *mockWarpmenuentryClient_Update_Call) Run(run func(ctx context.Context, warpMenuEntry *v1.WarpMenuEntry, opts v10.UpdateOptions)) *mockWarpmenuentryClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.WarpMenuEntry
		if args[1] != nil {
			arg1 = args[1].(*v1.WarpMenuEntry)
		}
		var arg2 v10.UpdateOptions
		if args[2] != nil {
			arg2 = args[2].(v10.UpdateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockWarpmenuentryClient_Update_Call) Return(warpMenuEntry1 *v1.WarpMenuEntry, err error) *mockWarpmenuentryClient_Update_Call {
	_c.Call.Return(warpMenuEntry1, err)
	return _c
}

func (_c *mockWarpmenuentryClient_Update_Call) RunAndReturn(run func(ctx context.Context, warpMenuEntry *v1.WarpMenuEntry, opts v10.UpdateOptions) (*v1.WarpMenuEntry, error)) *mockWarpmenuentryClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
