// Code generated by mockery v2.53.6. DO NOT EDIT.

package warpmenuentry

import (
	context "context"

	dogu "github.com/cloudogu/ces-commons-lib/dogu"
	mock "github.com/stretchr/testify/mock"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// EnsureWarpMenuEntry provides a mock function with given fields: ctx, doguResource
func (_m *MockManager) EnsureWarpMenuEntry(ctx context.Context, doguResource *v2.Dogu) error {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for EnsureWarpMenuEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) error); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_EnsureWarpMenuEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureWarpMenuEntry'
type MockManager_EnsureWarpMenuEntry_Call struct {
	*mock.Call
}

// EnsureWarpMenuEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *MockManager_Expecter) EnsureWarpMenuEntry(ctx interface{}, doguResource interface{}) *MockManager_EnsureWarpMenuEntry_Call {
	return &MockManager_EnsureWarpMenuEntry_Call{Call: _e.mock.On("EnsureWarpMenuEntry", ctx, doguResource)}
}

func (_c *MockManager_EnsureWarpMenuEntry_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *MockManager_EnsureWarpMenuEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *MockManager_EnsureWarpMenuEntry_Call) Return(_a0 error) *MockManager_EnsureWarpMenuEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_EnsureWarpMenuEntry_Call) RunAndReturn(run func(context.Context, *v2.Dogu) error) *MockManager_EnsureWarpMenuEntry_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWarpMenuEntry provides a mock function with given fields: ctx, doguName
func (_m *MockManager) RemoveWarpMenuEntry(ctx context.Context, doguName dogu.SimpleName) error {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWarpMenuEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) error); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_RemoveWarpMenuEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWarpMenuEntry'
type MockManager_RemoveWarpMenuEntry_Call struct {
	*mock.Call
}

// RemoveWarpMenuEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName dogu.SimpleName
func (_e *MockManager_Expecter) RemoveWarpMenuEntry(ctx interface{}, doguName interface{}) *MockManager_RemoveWarpMenuEntry_Call {
	return &MockManager_RemoveWarpMenuEntry_Call{Call: _e.mock.On("RemoveWarpMenuEntry", ctx, doguName)}
}

func (_c *MockManager_RemoveWarpMenuEntry_Call) Run(run func(ctx context.Context, doguName dogu.SimpleName)) *MockManager_RemoveWarpMenuEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dogu.SimpleName))
	})
	return _c
}

func (_c *MockManager_RemoveWarpMenuEntry_Call) Return(_a0 error) *MockManager_RemoveWarpMenuEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_RemoveWarpMenuEntry_Call) RunAndReturn(run func(context.Context, dogu.SimpleName) error) *MockManager_RemoveWarpMenuEntry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
