// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/cloudogu/k8s-dogu-operator/api/v1"
)

// SupportManager is an autogenerated mock type for the SupportManager type
type SupportManager struct {
	mock.Mock
}

// HandleSupportMode provides a mock function with given fields: ctx, doguResource
func (_m *SupportManager) HandleSupportMode(ctx context.Context, doguResource *v1.Dogu) (bool, error) {
	ret := _m.Called(ctx, doguResource)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Dogu) bool); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.Dogu) error); ok {
		r1 = rf(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSupportManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewSupportManager creates a new instance of SupportManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSupportManager(t mockConstructorTestingTNewSupportManager) *SupportManager {
	mock := &SupportManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
