// Code generated by mockery v2.53.3. DO NOT EDIT.

package usecase

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
)

// mockDoguUsecase is an autogenerated mock type for the doguUsecase type
type mockDoguUsecase struct {
	mock.Mock
}

type mockDoguUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguUsecase) EXPECT() *mockDoguUsecase_Expecter {
	return &mockDoguUsecase_Expecter{mock: &_m.Mock}
}

// HandleUntilApplied provides a mock function with given fields: ctx, doguResource
func (_m *mockDoguUsecase) HandleUntilApplied(ctx context.Context, doguResource *v2.Dogu) (time.Duration, error) {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for HandleUntilApplied")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) (time.Duration, error)); ok {
		return rf(ctx, doguResource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) time.Duration); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.Dogu) error); ok {
		r1 = rf(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguUsecase_HandleUntilApplied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUntilApplied'
type mockDoguUsecase_HandleUntilApplied_Call struct {
	*mock.Call
}

// HandleUntilApplied is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *mockDoguUsecase_Expecter) HandleUntilApplied(ctx interface{}, doguResource interface{}) *mockDoguUsecase_HandleUntilApplied_Call {
	return &mockDoguUsecase_HandleUntilApplied_Call{Call: _e.mock.On("HandleUntilApplied", ctx, doguResource)}
}

func (_c *mockDoguUsecase_HandleUntilApplied_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *mockDoguUsecase_HandleUntilApplied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *mockDoguUsecase_HandleUntilApplied_Call) Return(_a0 time.Duration, _a1 error) *mockDoguUsecase_HandleUntilApplied_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguUsecase_HandleUntilApplied_Call) RunAndReturn(run func(context.Context, *v2.Dogu) (time.Duration, error)) *mockDoguUsecase_HandleUntilApplied_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguUsecase creates a new instance of mockDoguUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguUsecase {
	mock := &mockDoguUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
