// Code generated by mockery v2.53.5. DO NOT EDIT.

package main

import (
	context "context"

	corev1 "k8s.io/api/core/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/client-go/applyconfigurations/core/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// mockPvcInterface is an autogenerated mock type for the pvcInterface type
type mockPvcInterface struct {
	mock.Mock
}

type mockPvcInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPvcInterface) EXPECT() *mockPvcInterface_Expecter {
	return &mockPvcInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *mockPvcInterface) Apply(ctx context.Context, persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration, opts metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type mockPvcInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *mockPvcInterface_Expecter) Apply(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *mockPvcInterface_Apply_Call {
	return &mockPvcInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, persistentVolumeClaim, opts)}
}

func (_c *mockPvcInterface_Apply_Call) Run(run func(ctx context.Context, persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration, opts metav1.ApplyOptions)) *mockPvcInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.PersistentVolumeClaimApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *mockPvcInterface_Apply_Call) Return(result *corev1.PersistentVolumeClaim, err error) *mockPvcInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockPvcInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error)) *mockPvcInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyStatus provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *mockPvcInterface) ApplyStatus(ctx context.Context, persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration, opts metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	if len(ret) == 0 {
		panic("no return value specified for ApplyStatus")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type mockPvcInterface_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *mockPvcInterface_Expecter) ApplyStatus(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *mockPvcInterface_ApplyStatus_Call {
	return &mockPvcInterface_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, persistentVolumeClaim, opts)}
}

func (_c *mockPvcInterface_ApplyStatus_Call) Run(run func(ctx context.Context, persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration, opts metav1.ApplyOptions)) *mockPvcInterface_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.PersistentVolumeClaimApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *mockPvcInterface_ApplyStatus_Call) Return(result *corev1.PersistentVolumeClaim, err error) *mockPvcInterface_ApplyStatus_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockPvcInterface_ApplyStatus_Call) RunAndReturn(run func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error)) *mockPvcInterface_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *mockPvcInterface) Create(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.CreateOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.CreateOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.CreateOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockPvcInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *corev1.PersistentVolumeClaim
//   - opts metav1.CreateOptions
func (_e *mockPvcInterface_Expecter) Create(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *mockPvcInterface_Create_Call {
	return &mockPvcInterface_Create_Call{Call: _e.mock.On("Create", ctx, persistentVolumeClaim, opts)}
}

func (_c *mockPvcInterface_Create_Call) Run(run func(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.CreateOptions)) *mockPvcInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.PersistentVolumeClaim), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockPvcInterface_Create_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *mockPvcInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcInterface_Create_Call) RunAndReturn(run func(context.Context, *corev1.PersistentVolumeClaim, metav1.CreateOptions) (*corev1.PersistentVolumeClaim, error)) *mockPvcInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockPvcInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockPvcInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockPvcInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockPvcInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockPvcInterface_Delete_Call {
	return &mockPvcInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockPvcInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockPvcInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockPvcInterface_Delete_Call) Return(_a0 error) *mockPvcInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockPvcInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockPvcInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *mockPvcInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockPvcInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type mockPvcInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *mockPvcInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *mockPvcInterface_DeleteCollection_Call {
	return &mockPvcInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *mockPvcInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *mockPvcInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockPvcInterface_DeleteCollection_Call) Return(_a0 error) *mockPvcInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockPvcInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *mockPvcInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockPvcInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockPvcInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockPvcInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockPvcInterface_Get_Call {
	return &mockPvcInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockPvcInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockPvcInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockPvcInterface_Get_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *mockPvcInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*corev1.PersistentVolumeClaim, error)) *mockPvcInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockPvcInterface) List(ctx context.Context, opts metav1.ListOptions) (*corev1.PersistentVolumeClaimList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *corev1.PersistentVolumeClaimList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*corev1.PersistentVolumeClaimList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *corev1.PersistentVolumeClaimList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaimList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockPvcInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockPvcInterface_Expecter) List(ctx interface{}, opts interface{}) *mockPvcInterface_List_Call {
	return &mockPvcInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockPvcInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockPvcInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockPvcInterface_List_Call) Return(_a0 *corev1.PersistentVolumeClaimList, _a1 error) *mockPvcInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*corev1.PersistentVolumeClaimList, error)) *mockPvcInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *mockPvcInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*corev1.PersistentVolumeClaim, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type mockPvcInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *mockPvcInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *mockPvcInterface_Patch_Call {
	return &mockPvcInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *mockPvcInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *mockPvcInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *mockPvcInterface_Patch_Call) Return(result *corev1.PersistentVolumeClaim, err error) *mockPvcInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockPvcInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*corev1.PersistentVolumeClaim, error)) *mockPvcInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *mockPvcInterface) Update(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockPvcInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *corev1.PersistentVolumeClaim
//   - opts metav1.UpdateOptions
func (_e *mockPvcInterface_Expecter) Update(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *mockPvcInterface_Update_Call {
	return &mockPvcInterface_Update_Call{Call: _e.mock.On("Update", ctx, persistentVolumeClaim, opts)}
}

func (_c *mockPvcInterface_Update_Call) Run(run func(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.UpdateOptions)) *mockPvcInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.PersistentVolumeClaim), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockPvcInterface_Update_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *mockPvcInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcInterface_Update_Call) RunAndReturn(run func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)) *mockPvcInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *mockPvcInterface) UpdateStatus(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type mockPvcInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *corev1.PersistentVolumeClaim
//   - opts metav1.UpdateOptions
func (_e *mockPvcInterface_Expecter) UpdateStatus(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *mockPvcInterface_UpdateStatus_Call {
	return &mockPvcInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, persistentVolumeClaim, opts)}
}

func (_c *mockPvcInterface_UpdateStatus_Call) Run(run func(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.UpdateOptions)) *mockPvcInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.PersistentVolumeClaim), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockPvcInterface_UpdateStatus_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *mockPvcInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)) *mockPvcInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockPvcInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockPvcInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockPvcInterface_Expecter) Watch(ctx interface{}, opts interface{}) *mockPvcInterface_Watch_Call {
	return &mockPvcInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockPvcInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockPvcInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockPvcInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockPvcInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *mockPvcInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPvcInterface creates a new instance of mockPvcInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPvcInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPvcInterface {
	mock := &mockPvcInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
