// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	bytes "bytes"
	context "context"

	mock "github.com/stretchr/testify/mock"

	resource "github.com/cloudogu/k8s-dogu-operator/controllers/resource"
)

// CommandDoguExecutor is an autogenerated mock type for the CommandDoguExecutor type
type CommandDoguExecutor struct {
	mock.Mock
}

// ExecCommandForDogu provides a mock function with given fields: ctx, doguName, namespace, command
func (_m *CommandDoguExecutor) ExecCommandForDogu(ctx context.Context, doguName string, namespace string, command *resource.ShellCommand) (*bytes.Buffer, error) {
	ret := _m.Called(ctx, doguName, namespace, command)

	var r0 *bytes.Buffer
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *resource.ShellCommand) *bytes.Buffer); ok {
		r0 = rf(ctx, doguName, namespace, command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, *resource.ShellCommand) error); ok {
		r1 = rf(ctx, doguName, namespace, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCommandDoguExecutor interface {
	mock.TestingT
	Cleanup(func())
}

// NewCommandDoguExecutor creates a new instance of CommandDoguExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommandDoguExecutor(t mockConstructorTestingTNewCommandDoguExecutor) *CommandDoguExecutor {
	mock := &CommandDoguExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
