// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// ServiceAccountCreator is an autogenerated mock type for the ServiceAccountCreator type
type ServiceAccountCreator struct {
	mock.Mock
}

// CreateAll provides a mock function with given fields: ctx, namespace, dogu
func (_m *ServiceAccountCreator) CreateAll(ctx context.Context, namespace string, dogu *core.Dogu) error {
	ret := _m.Called(ctx, namespace, dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *core.Dogu) error); ok {
		r0 = rf(ctx, namespace, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewServiceAccountCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceAccountCreator creates a new instance of ServiceAccountCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceAccountCreator(t mockConstructorTestingTNewServiceAccountCreator) *ServiceAccountCreator {
	mock := &ServiceAccountCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
