// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package imageregistry

import (
	"context"

	"github.com/google/go-containerregistry/pkg/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageRegistry creates a new instance of MockImageRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageRegistry {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockImageRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockImageRegistry is an autogenerated mock type for the ImageRegistry type
type MockImageRegistry struct {
	mock.Mock
}

type MockImageRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageRegistry) EXPECT() *MockImageRegistry_Expecter {
	return &MockImageRegistry_Expecter{mock: &_m.Mock}
}

// PullImageConfig provides a mock function for the type MockImageRegistry
func (_mock *MockImageRegistry) PullImageConfig(ctx context.Context, image string) (*v1.ConfigFile, error) {
	ret := _mock.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for PullImageConfig")
	}

	var r0 *v1.ConfigFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.ConfigFile, error)); ok {
		return returnFunc(ctx, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.ConfigFile); ok {
		r0 = returnFunc(ctx, image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRegistry_PullImageConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullImageConfig'
type MockImageRegistry_PullImageConfig_Call struct {
	*mock.Call
}

// PullImageConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
func (_e *MockImageRegistry_Expecter) PullImageConfig(ctx any, image any) *MockImageRegistry_PullImageConfig_Call {
	return &MockImageRegistry_PullImageConfig_Call{Call: _e.mock.On("PullImageConfig", ctx, image)}
}

func (_c *MockImageRegistry_PullImageConfig_Call) Run(run func(ctx context.Context, image string)) *MockImageRegistry_PullImageConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRegistry_PullImageConfig_Call) Return(configFile *v1.ConfigFile, err error) *MockImageRegistry_PullImageConfig_Call {
	_c.Call.Return(configFile, err)
	return _c
}

func (_c *MockImageRegistry_PullImageConfig_Call) RunAndReturn(run func(ctx context.Context, image string) (*v1.ConfigFile, error)) *MockImageRegistry_PullImageConfig_Call {
	_c.Call.Return(run)
	return _c
}
