apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: k8s-dogu-operator
        app: ces
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - --leader-elect
        env:
          - name: STAGE
            value: "production"
          - name: LOG_LEVEL
            value: "debug"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DOGU_REGISTRY_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: k8s-dogu-operator-dogu-registry
                key: endpoint
          - name: DOGU_REGISTRY_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8s-dogu-operator-dogu-registry
                key: username
          - name: DOGU_REGISTRY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8s-dogu-operator-dogu-registry
                key: password
          - name: DOCKER_REGISTRY
            valueFrom:
              secretKeyRef:
                name: k8s-dogu-operator-docker-registry
                key: .dockerconfigjson
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
