// Code generated by mockery v2.53.5. DO NOT EDIT.

package controllers

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
)

// MockDoguInstallOrChangeUseCase is an autogenerated mock type for the DoguInstallOrChangeUseCase type
type MockDoguInstallOrChangeUseCase struct {
	mock.Mock
}

type MockDoguInstallOrChangeUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguInstallOrChangeUseCase) EXPECT() *MockDoguInstallOrChangeUseCase_Expecter {
	return &MockDoguInstallOrChangeUseCase_Expecter{mock: &_m.Mock}
}

// HandleUntilApplied provides a mock function with given fields: ctx, doguResource
func (_m *MockDoguInstallOrChangeUseCase) HandleUntilApplied(ctx context.Context, doguResource *v2.Dogu) (time.Duration, bool, error) {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for HandleUntilApplied")
	}

	var r0 time.Duration
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) (time.Duration, bool, error)); ok {
		return rf(ctx, doguResource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) time.Duration); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.Dogu) bool); ok {
		r1 = rf(ctx, doguResource)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *v2.Dogu) error); ok {
		r2 = rf(ctx, doguResource)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUntilApplied'
type MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call struct {
	*mock.Call
}

// HandleUntilApplied is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *MockDoguInstallOrChangeUseCase_Expecter) HandleUntilApplied(ctx interface{}, doguResource interface{}) *MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call {
	return &MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call{Call: _e.mock.On("HandleUntilApplied", ctx, doguResource)}
}

func (_c *MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call) Return(_a0 time.Duration, _a1 bool, _a2 error) *MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call) RunAndReturn(run func(context.Context, *v2.Dogu) (time.Duration, bool, error)) *MockDoguInstallOrChangeUseCase_HandleUntilApplied_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguInstallOrChangeUseCase creates a new instance of MockDoguInstallOrChangeUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguInstallOrChangeUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguInstallOrChangeUseCase {
	mock := &MockDoguInstallOrChangeUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
