// Code generated by mockery v2.46.2. DO NOT EDIT.

package controllers

import (
	context "context"

	v2 "github.com/cloudogu/k8s-dogu-operator/v2/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// MockInstallManager is an autogenerated mock type for the InstallManager type
type MockInstallManager struct {
	mock.Mock
}

type MockInstallManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallManager) EXPECT() *MockInstallManager_Expecter {
	return &MockInstallManager_Expecter{mock: &_m.Mock}
}

// Install provides a mock function with given fields: ctx, doguResource
func (_m *MockInstallManager) Install(ctx context.Context, doguResource *v2.Dogu) error {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) error); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInstallManager_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockInstallManager_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *MockInstallManager_Expecter) Install(ctx interface{}, doguResource interface{}) *MockInstallManager_Install_Call {
	return &MockInstallManager_Install_Call{Call: _e.mock.On("Install", ctx, doguResource)}
}

func (_c *MockInstallManager_Install_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *MockInstallManager_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *MockInstallManager_Install_Call) Return(_a0 error) *MockInstallManager_Install_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInstallManager_Install_Call) RunAndReturn(run func(context.Context, *v2.Dogu) error) *MockInstallManager_Install_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstallManager creates a new instance of MockInstallManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallManager {
	mock := &MockInstallManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
