// Code generated by mockery v2.46.2. DO NOT EDIT.

package controllers

import (
	context "context"

	v2 "github.com/cloudogu/k8s-dogu-operator/v3/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// mockUpgradeManager is an autogenerated mock type for the upgradeManager type
type mockUpgradeManager struct {
	mock.Mock
}

type mockUpgradeManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUpgradeManager) EXPECT() *mockUpgradeManager_Expecter {
	return &mockUpgradeManager_Expecter{mock: &_m.Mock}
}

// Upgrade provides a mock function with given fields: ctx, doguResource
func (_m *mockUpgradeManager) Upgrade(ctx context.Context, doguResource *v2.Dogu) error {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for Upgrade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) error); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockUpgradeManager_Upgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upgrade'
type mockUpgradeManager_Upgrade_Call struct {
	*mock.Call
}

// Upgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *mockUpgradeManager_Expecter) Upgrade(ctx interface{}, doguResource interface{}) *mockUpgradeManager_Upgrade_Call {
	return &mockUpgradeManager_Upgrade_Call{Call: _e.mock.On("Upgrade", ctx, doguResource)}
}

func (_c *mockUpgradeManager_Upgrade_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *mockUpgradeManager_Upgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *mockUpgradeManager_Upgrade_Call) Return(_a0 error) *mockUpgradeManager_Upgrade_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockUpgradeManager_Upgrade_Call) RunAndReturn(run func(context.Context, *v2.Dogu) error) *mockUpgradeManager_Upgrade_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUpgradeManager creates a new instance of mockUpgradeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUpgradeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUpgradeManager {
	mock := &mockUpgradeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
