// Code generated by mockery v2.46.2. DO NOT EDIT.

package controllers

import (
	core "github.com/cloudogu/cesapp-lib/core"
	exec "github.com/cloudogu/k8s-dogu-operator/v2/controllers/exec"
	mock "github.com/stretchr/testify/mock"

	v2 "github.com/cloudogu/k8s-dogu-operator/v2/api/v2"
)

// MockExecPodFactory is an autogenerated mock type for the ExecPodFactory type
type MockExecPodFactory struct {
	mock.Mock
}

type MockExecPodFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecPodFactory) EXPECT() *MockExecPodFactory_Expecter {
	return &MockExecPodFactory_Expecter{mock: &_m.Mock}
}

// NewExecPod provides a mock function with given fields: doguResource, dogu
func (_m *MockExecPodFactory) NewExecPod(doguResource *v2.Dogu, dogu *core.Dogu) (exec.ExecPod, error) {
	ret := _m.Called(doguResource, dogu)

	if len(ret) == 0 {
		panic("no return value specified for NewExecPod")
	}

	var r0 exec.ExecPod
	var r1 error
	if rf, ok := ret.Get(0).(func(*v2.Dogu, *core.Dogu) (exec.ExecPod, error)); ok {
		return rf(doguResource, dogu)
	}
	if rf, ok := ret.Get(0).(func(*v2.Dogu, *core.Dogu) exec.ExecPod); ok {
		r0 = rf(doguResource, dogu)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exec.ExecPod)
		}
	}

	if rf, ok := ret.Get(1).(func(*v2.Dogu, *core.Dogu) error); ok {
		r1 = rf(doguResource, dogu)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecPodFactory_NewExecPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewExecPod'
type MockExecPodFactory_NewExecPod_Call struct {
	*mock.Call
}

// NewExecPod is a helper method to define mock.On call
//   - doguResource *v2.Dogu
//   - dogu *core.Dogu
func (_e *MockExecPodFactory_Expecter) NewExecPod(doguResource interface{}, dogu interface{}) *MockExecPodFactory_NewExecPod_Call {
	return &MockExecPodFactory_NewExecPod_Call{Call: _e.mock.On("NewExecPod", doguResource, dogu)}
}

func (_c *MockExecPodFactory_NewExecPod_Call) Run(run func(doguResource *v2.Dogu, dogu *core.Dogu)) *MockExecPodFactory_NewExecPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v2.Dogu), args[1].(*core.Dogu))
	})
	return _c
}

func (_c *MockExecPodFactory_NewExecPod_Call) Return(_a0 exec.ExecPod, _a1 error) *MockExecPodFactory_NewExecPod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecPodFactory_NewExecPod_Call) RunAndReturn(run func(*v2.Dogu, *core.Dogu) (exec.ExecPod, error)) *MockExecPodFactory_NewExecPod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecPodFactory creates a new instance of MockExecPodFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecPodFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecPodFactory {
	mock := &MockExecPodFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
