// Code generated by mockery v2.53.7. DO NOT EDIT.

package controllers

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	v3beta1 "github.com/cloudogu/k8s-dogu-lib/v3/api/v3beta1"
)

// MockDoguV3Usecase is an autogenerated mock type for the DoguV3Usecase type
type MockDoguV3Usecase struct {
	mock.Mock
}

type MockDoguV3Usecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguV3Usecase) EXPECT() *MockDoguV3Usecase_Expecter {
	return &MockDoguV3Usecase_Expecter{mock: &_m.Mock}
}

// HandleUntilApplied provides a mock function with given fields: ctx, doguResource
func (_m *MockDoguV3Usecase) HandleUntilApplied(ctx context.Context, doguResource *v3beta1.Dogu) (time.Duration, error) {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for HandleUntilApplied")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu) (time.Duration, error)); ok {
		return rf(ctx, doguResource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu) time.Duration); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v3beta1.Dogu) error); ok {
		r1 = rf(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguV3Usecase_HandleUntilApplied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUntilApplied'
type MockDoguV3Usecase_HandleUntilApplied_Call struct {
	*mock.Call
}

// HandleUntilApplied is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v3beta1.Dogu
func (_e *MockDoguV3Usecase_Expecter) HandleUntilApplied(ctx interface{}, doguResource interface{}) *MockDoguV3Usecase_HandleUntilApplied_Call {
	return &MockDoguV3Usecase_HandleUntilApplied_Call{Call: _e.mock.On("HandleUntilApplied", ctx, doguResource)}
}

func (_c *MockDoguV3Usecase_HandleUntilApplied_Call) Run(run func(ctx context.Context, doguResource *v3beta1.Dogu)) *MockDoguV3Usecase_HandleUntilApplied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v3beta1.Dogu))
	})
	return _c
}

func (_c *MockDoguV3Usecase_HandleUntilApplied_Call) Return(_a0 time.Duration, _a1 error) *MockDoguV3Usecase_HandleUntilApplied_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguV3Usecase_HandleUntilApplied_Call) RunAndReturn(run func(context.Context, *v3beta1.Dogu) (time.Duration, error)) *MockDoguV3Usecase_HandleUntilApplied_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguV3Usecase creates a new instance of MockDoguV3Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguV3Usecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguV3Usecase {
	mock := &MockDoguV3Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
