// Code generated by mockery v2.46.2. DO NOT EDIT.

package controllers

import (
	ecoSystem "github.com/cloudogu/k8s-dogu-operator/v2/api/ecoSystem"
	mock "github.com/stretchr/testify/mock"
)

// MockEcosystemInterface is an autogenerated mock type for the EcosystemInterface type
type MockEcosystemInterface struct {
	mock.Mock
}

type MockEcosystemInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEcosystemInterface) EXPECT() *MockEcosystemInterface_Expecter {
	return &MockEcosystemInterface_Expecter{mock: &_m.Mock}
}

// DoguRestarts provides a mock function with given fields: namespace
func (_m *MockEcosystemInterface) DoguRestarts(namespace string) ecoSystem.DoguRestartInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for DoguRestarts")
	}

	var r0 ecoSystem.DoguRestartInterface
	if rf, ok := ret.Get(0).(func(string) ecoSystem.DoguRestartInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ecoSystem.DoguRestartInterface)
		}
	}

	return r0
}

// MockEcosystemInterface_DoguRestarts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoguRestarts'
type MockEcosystemInterface_DoguRestarts_Call struct {
	*mock.Call
}

// DoguRestarts is a helper method to define mock.On call
//   - namespace string
func (_e *MockEcosystemInterface_Expecter) DoguRestarts(namespace interface{}) *MockEcosystemInterface_DoguRestarts_Call {
	return &MockEcosystemInterface_DoguRestarts_Call{Call: _e.mock.On("DoguRestarts", namespace)}
}

func (_c *MockEcosystemInterface_DoguRestarts_Call) Run(run func(namespace string)) *MockEcosystemInterface_DoguRestarts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEcosystemInterface_DoguRestarts_Call) Return(_a0 ecoSystem.DoguRestartInterface) *MockEcosystemInterface_DoguRestarts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemInterface_DoguRestarts_Call) RunAndReturn(run func(string) ecoSystem.DoguRestartInterface) *MockEcosystemInterface_DoguRestarts_Call {
	_c.Call.Return(run)
	return _c
}

// Dogus provides a mock function with given fields: namespace
func (_m *MockEcosystemInterface) Dogus(namespace string) ecoSystem.DoguInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Dogus")
	}

	var r0 ecoSystem.DoguInterface
	if rf, ok := ret.Get(0).(func(string) ecoSystem.DoguInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ecoSystem.DoguInterface)
		}
	}

	return r0
}

// MockEcosystemInterface_Dogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dogus'
type MockEcosystemInterface_Dogus_Call struct {
	*mock.Call
}

// Dogus is a helper method to define mock.On call
//   - namespace string
func (_e *MockEcosystemInterface_Expecter) Dogus(namespace interface{}) *MockEcosystemInterface_Dogus_Call {
	return &MockEcosystemInterface_Dogus_Call{Call: _e.mock.On("Dogus", namespace)}
}

func (_c *MockEcosystemInterface_Dogus_Call) Run(run func(namespace string)) *MockEcosystemInterface_Dogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEcosystemInterface_Dogus_Call) Return(_a0 ecoSystem.DoguInterface) *MockEcosystemInterface_Dogus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcosystemInterface_Dogus_Call) RunAndReturn(run func(string) ecoSystem.DoguInterface) *MockEcosystemInterface_Dogus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEcosystemInterface creates a new instance of MockEcosystemInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEcosystemInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEcosystemInterface {
	mock := &MockEcosystemInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
