// Code generated by mockery v2.46.2. DO NOT EDIT.

package controllers

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// MockRequirementsGenerator is an autogenerated mock type for the RequirementsGenerator type
type MockRequirementsGenerator struct {
	mock.Mock
}

type MockRequirementsGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequirementsGenerator) EXPECT() *MockRequirementsGenerator_Expecter {
	return &MockRequirementsGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx, dogu
func (_m *MockRequirementsGenerator) Generate(ctx context.Context, dogu *core.Dogu) (v1.ResourceRequirements, error) {
	ret := _m.Called(ctx, dogu)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 v1.ResourceRequirements
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.Dogu) (v1.ResourceRequirements, error)); ok {
		return rf(ctx, dogu)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *core.Dogu) v1.ResourceRequirements); ok {
		r0 = rf(ctx, dogu)
	} else {
		r0 = ret.Get(0).(v1.ResourceRequirements)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *core.Dogu) error); ok {
		r1 = rf(ctx, dogu)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequirementsGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockRequirementsGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu *core.Dogu
func (_e *MockRequirementsGenerator_Expecter) Generate(ctx interface{}, dogu interface{}) *MockRequirementsGenerator_Generate_Call {
	return &MockRequirementsGenerator_Generate_Call{Call: _e.mock.On("Generate", ctx, dogu)}
}

func (_c *MockRequirementsGenerator_Generate_Call) Run(run func(ctx context.Context, dogu *core.Dogu)) *MockRequirementsGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.Dogu))
	})
	return _c
}

func (_c *MockRequirementsGenerator_Generate_Call) Return(_a0 v1.ResourceRequirements, _a1 error) *MockRequirementsGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequirementsGenerator_Generate_Call) RunAndReturn(run func(context.Context, *core.Dogu) (v1.ResourceRequirements, error)) *MockRequirementsGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequirementsGenerator creates a new instance of MockRequirementsGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequirementsGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequirementsGenerator {
	mock := &MockRequirementsGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
