// Code generated by mockery v2.53.6. DO NOT EDIT.

package controllers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	controllerruntime "sigs.k8s.io/controller-runtime"

	v3beta1 "github.com/cloudogu/k8s-dogu-lib/v3/api/v3beta1"
)

// MockRequeueHandlerV3 is an autogenerated mock type for the RequeueHandlerV3 type
type MockRequeueHandlerV3 struct {
	mock.Mock
}

type MockRequeueHandlerV3_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequeueHandlerV3) EXPECT() *MockRequeueHandlerV3_Expecter {
	return &MockRequeueHandlerV3_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, doguResource
func (_m *MockRequeueHandlerV3) Handle(ctx context.Context, doguResource *v3beta1.Dogu) (controllerruntime.Result, error) {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 controllerruntime.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu) (controllerruntime.Result, error)); ok {
		return rf(ctx, doguResource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu) controllerruntime.Result); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Get(0).(controllerruntime.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v3beta1.Dogu) error); ok {
		r1 = rf(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequeueHandlerV3_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockRequeueHandlerV3_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v3beta1.Dogu
func (_e *MockRequeueHandlerV3_Expecter) Handle(ctx interface{}, doguResource interface{}) *MockRequeueHandlerV3_Handle_Call {
	return &MockRequeueHandlerV3_Handle_Call{Call: _e.mock.On("Handle", ctx, doguResource)}
}

func (_c *MockRequeueHandlerV3_Handle_Call) Run(run func(ctx context.Context, doguResource *v3beta1.Dogu)) *MockRequeueHandlerV3_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v3beta1.Dogu))
	})
	return _c
}

func (_c *MockRequeueHandlerV3_Handle_Call) Return(result controllerruntime.Result, requeueErr error) *MockRequeueHandlerV3_Handle_Call {
	_c.Call.Return(result, requeueErr)
	return _c
}

func (_c *MockRequeueHandlerV3_Handle_Call) RunAndReturn(run func(context.Context, *v3beta1.Dogu) (controllerruntime.Result, error)) *MockRequeueHandlerV3_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequeueHandlerV3 creates a new instance of MockRequeueHandlerV3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequeueHandlerV3(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequeueHandlerV3 {
	mock := &MockRequeueHandlerV3{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
