apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
  labels:
    app: ces
    app.kubernetes.io/name: k8s-dogu-operator
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get