---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: k8s-dogu-operator
  labels:
    app: k8s-dogu-operator
    app.kubernetes.io/name: k8s-dogu-operator
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - patch
      - update
      - delete