---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  labels:
    app: ces
    app.kubernetes.io/name: k8s-dogu-operator
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"
