// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// TcpUpdServiceExposer is an autogenerated mock type for the TcpUpdServiceExposer type
type TcpUpdServiceExposer struct {
	mock.Mock
}

type TcpUpdServiceExposer_Expecter struct {
	mock *mock.Mock
}

func (_m *TcpUpdServiceExposer) EXPECT() *TcpUpdServiceExposer_Expecter {
	return &TcpUpdServiceExposer_Expecter{mock: &_m.Mock}
}

// DeleteDoguServices provides a mock function with given fields: ctx, namespace, dogu
func (_m *TcpUpdServiceExposer) DeleteDoguServices(ctx context.Context, namespace string, dogu *core.Dogu) error {
	ret := _m.Called(ctx, namespace, dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *core.Dogu) error); ok {
		r0 = rf(ctx, namespace, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TcpUpdServiceExposer_DeleteDoguServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDoguServices'
type TcpUpdServiceExposer_DeleteDoguServices_Call struct {
	*mock.Call
}

// DeleteDoguServices is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - dogu *core.Dogu
func (_e *TcpUpdServiceExposer_Expecter) DeleteDoguServices(ctx interface{}, namespace interface{}, dogu interface{}) *TcpUpdServiceExposer_DeleteDoguServices_Call {
	return &TcpUpdServiceExposer_DeleteDoguServices_Call{Call: _e.mock.On("DeleteDoguServices", ctx, namespace, dogu)}
}

func (_c *TcpUpdServiceExposer_DeleteDoguServices_Call) Run(run func(ctx context.Context, namespace string, dogu *core.Dogu)) *TcpUpdServiceExposer_DeleteDoguServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*core.Dogu))
	})
	return _c
}

func (_c *TcpUpdServiceExposer_DeleteDoguServices_Call) Return(_a0 error) *TcpUpdServiceExposer_DeleteDoguServices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TcpUpdServiceExposer_DeleteDoguServices_Call) RunAndReturn(run func(context.Context, string, *core.Dogu) error) *TcpUpdServiceExposer_DeleteDoguServices_Call {
	_c.Call.Return(run)
	return _c
}

// ExposeOrUpdateDoguServices provides a mock function with given fields: ctx, namespace, dogu
func (_m *TcpUpdServiceExposer) ExposeOrUpdateDoguServices(ctx context.Context, namespace string, dogu *core.Dogu) error {
	ret := _m.Called(ctx, namespace, dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *core.Dogu) error); ok {
		r0 = rf(ctx, namespace, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExposeOrUpdateDoguServices'
type TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call struct {
	*mock.Call
}

// ExposeOrUpdateDoguServices is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - dogu *core.Dogu
func (_e *TcpUpdServiceExposer_Expecter) ExposeOrUpdateDoguServices(ctx interface{}, namespace interface{}, dogu interface{}) *TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call {
	return &TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call{Call: _e.mock.On("ExposeOrUpdateDoguServices", ctx, namespace, dogu)}
}

func (_c *TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call) Run(run func(ctx context.Context, namespace string, dogu *core.Dogu)) *TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*core.Dogu))
	})
	return _c
}

func (_c *TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call) Return(_a0 error) *TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call) RunAndReturn(run func(context.Context, string, *core.Dogu) error) *TcpUpdServiceExposer_ExposeOrUpdateDoguServices_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewTcpUpdServiceExposer interface {
	mock.TestingT
	Cleanup(func())
}

// NewTcpUpdServiceExposer creates a new instance of TcpUpdServiceExposer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTcpUpdServiceExposer(t mockConstructorTestingTNewTcpUpdServiceExposer) *TcpUpdServiceExposer {
	mock := &TcpUpdServiceExposer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
