// Code generated by mockery v2.53.5. DO NOT EDIT.

package manager

import (
	context "context"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// MockAdditionalMountManager is an autogenerated mock type for the AdditionalMountManager type
type MockAdditionalMountManager struct {
	mock.Mock
}

type MockAdditionalMountManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdditionalMountManager) EXPECT() *MockAdditionalMountManager_Expecter {
	return &MockAdditionalMountManager_Expecter{mock: &_m.Mock}
}

// AdditionalMountsChanged provides a mock function with given fields: ctx, doguResource
func (_m *MockAdditionalMountManager) AdditionalMountsChanged(ctx context.Context, doguResource *v2.Dogu) (bool, error) {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for AdditionalMountsChanged")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) (bool, error)); ok {
		return rf(ctx, doguResource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) bool); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.Dogu) error); ok {
		r1 = rf(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdditionalMountManager_AdditionalMountsChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdditionalMountsChanged'
type MockAdditionalMountManager_AdditionalMountsChanged_Call struct {
	*mock.Call
}

// AdditionalMountsChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *MockAdditionalMountManager_Expecter) AdditionalMountsChanged(ctx interface{}, doguResource interface{}) *MockAdditionalMountManager_AdditionalMountsChanged_Call {
	return &MockAdditionalMountManager_AdditionalMountsChanged_Call{Call: _e.mock.On("AdditionalMountsChanged", ctx, doguResource)}
}

func (_c *MockAdditionalMountManager_AdditionalMountsChanged_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *MockAdditionalMountManager_AdditionalMountsChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *MockAdditionalMountManager_AdditionalMountsChanged_Call) Return(_a0 bool, _a1 error) *MockAdditionalMountManager_AdditionalMountsChanged_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdditionalMountManager_AdditionalMountsChanged_Call) RunAndReturn(run func(context.Context, *v2.Dogu) (bool, error)) *MockAdditionalMountManager_AdditionalMountsChanged_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAdditionalMounts provides a mock function with given fields: ctx, doguResource
func (_m *MockAdditionalMountManager) UpdateAdditionalMounts(ctx context.Context, doguResource *v2.Dogu) error {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAdditionalMounts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) error); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdditionalMountManager_UpdateAdditionalMounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAdditionalMounts'
type MockAdditionalMountManager_UpdateAdditionalMounts_Call struct {
	*mock.Call
}

// UpdateAdditionalMounts is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *MockAdditionalMountManager_Expecter) UpdateAdditionalMounts(ctx interface{}, doguResource interface{}) *MockAdditionalMountManager_UpdateAdditionalMounts_Call {
	return &MockAdditionalMountManager_UpdateAdditionalMounts_Call{Call: _e.mock.On("UpdateAdditionalMounts", ctx, doguResource)}
}

func (_c *MockAdditionalMountManager_UpdateAdditionalMounts_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *MockAdditionalMountManager_UpdateAdditionalMounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *MockAdditionalMountManager_UpdateAdditionalMounts_Call) Return(_a0 error) *MockAdditionalMountManager_UpdateAdditionalMounts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdditionalMountManager_UpdateAdditionalMounts_Call) RunAndReturn(run func(context.Context, *v2.Dogu) error) *MockAdditionalMountManager_UpdateAdditionalMounts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdditionalMountManager creates a new instance of MockAdditionalMountManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdditionalMountManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdditionalMountManager {
	mock := &MockAdditionalMountManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
