// Code generated by mockery v2.53.3. DO NOT EDIT.

package manager

import (
	context "context"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// MockDoguRestartManager is an autogenerated mock type for the DoguRestartManager type
type MockDoguRestartManager struct {
	mock.Mock
}

type MockDoguRestartManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguRestartManager) EXPECT() *MockDoguRestartManager_Expecter {
	return &MockDoguRestartManager_Expecter{mock: &_m.Mock}
}

// RestartDogu provides a mock function with given fields: ctx, dogu
func (_m *MockDoguRestartManager) RestartDogu(ctx context.Context, dogu *v2.Dogu) error {
	ret := _m.Called(ctx, dogu)

	if len(ret) == 0 {
		panic("no return value specified for RestartDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) error); ok {
		r0 = rf(ctx, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguRestartManager_RestartDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartDogu'
type MockDoguRestartManager_RestartDogu_Call struct {
	*mock.Call
}

// RestartDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu *v2.Dogu
func (_e *MockDoguRestartManager_Expecter) RestartDogu(ctx interface{}, dogu interface{}) *MockDoguRestartManager_RestartDogu_Call {
	return &MockDoguRestartManager_RestartDogu_Call{Call: _e.mock.On("RestartDogu", ctx, dogu)}
}

func (_c *MockDoguRestartManager_RestartDogu_Call) Run(run func(ctx context.Context, dogu *v2.Dogu)) *MockDoguRestartManager_RestartDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *MockDoguRestartManager_RestartDogu_Call) Return(_a0 error) *MockDoguRestartManager_RestartDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguRestartManager_RestartDogu_Call) RunAndReturn(run func(context.Context, *v2.Dogu) error) *MockDoguRestartManager_RestartDogu_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguRestartManager creates a new instance of MockDoguRestartManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguRestartManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguRestartManager {
	mock := &MockDoguRestartManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
