// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dependency

import (
	"context"

	"github.com/cloudogu/ces-commons-lib/dogu"
	"github.com/cloudogu/cesapp-lib/core"
	"github.com/cloudogu/k8s-dogu-lib/v3/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDependencyValidator creates a new instance of MockDependencyValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDependencyValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDependencyValidator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDependencyValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDependencyValidator is an autogenerated mock type for the DependencyValidator type
type MockDependencyValidator struct {
	mock.Mock
}

type MockDependencyValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDependencyValidator) EXPECT() *MockDependencyValidator_Expecter {
	return &MockDependencyValidator_Expecter{mock: &_m.Mock}
}

// ValidateAllDependencies provides a mock function for the type MockDependencyValidator
func (_mock *MockDependencyValidator) ValidateAllDependencies(ctx context.Context, dogu *core.Dogu) error {
	ret := _mock.Called(ctx, dogu)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAllDependencies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.Dogu) error); ok {
		r0 = returnFunc(ctx, dogu)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDependencyValidator_ValidateAllDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAllDependencies'
type MockDependencyValidator_ValidateAllDependencies_Call struct {
	*mock.Call
}

// ValidateAllDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu *core.Dogu
func (_e *MockDependencyValidator_Expecter) ValidateAllDependencies(ctx any, dogu any) *MockDependencyValidator_ValidateAllDependencies_Call {
	return &MockDependencyValidator_ValidateAllDependencies_Call{Call: _e.mock.On("ValidateAllDependencies", ctx, dogu)}
}

func (_c *MockDependencyValidator_ValidateAllDependencies_Call) Run(run func(ctx context.Context, dogu *core.Dogu)) *MockDependencyValidator_ValidateAllDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.Dogu
		if args[1] != nil {
			arg1 = args[1].(*core.Dogu)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDependencyValidator_ValidateAllDependencies_Call) Return(err error) *MockDependencyValidator_ValidateAllDependencies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDependencyValidator_ValidateAllDependencies_Call) RunAndReturn(run func(ctx context.Context, dogu *core.Dogu) error) *MockDependencyValidator_ValidateAllDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// newMockLocalDoguFetcher creates a new instance of mockLocalDoguFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLocalDoguFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLocalDoguFetcher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockLocalDoguFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockLocalDoguFetcher is an autogenerated mock type for the localDoguFetcher type
type mockLocalDoguFetcher struct {
	mock.Mock
}

type mockLocalDoguFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLocalDoguFetcher) EXPECT() *mockLocalDoguFetcher_Expecter {
	return &mockLocalDoguFetcher_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function for the type mockLocalDoguFetcher
func (_mock *mockLocalDoguFetcher) Enabled(ctx context.Context, doguName dogu.SimpleName) (bool, error) {
	ret := _mock.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) (bool, error)); ok {
		return returnFunc(ctx, doguName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) bool); ok {
		r0 = returnFunc(ctx, doguName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dogu.SimpleName) error); ok {
		r1 = returnFunc(ctx, doguName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockLocalDoguFetcher_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type mockLocalDoguFetcher_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName dogu.SimpleName
func (_e *mockLocalDoguFetcher_Expecter) Enabled(ctx any, doguName any) *mockLocalDoguFetcher_Enabled_Call {
	return &mockLocalDoguFetcher_Enabled_Call{Call: _e.mock.On("Enabled", ctx, doguName)}
}

func (_c *mockLocalDoguFetcher_Enabled_Call) Run(run func(ctx context.Context, doguName dogu.SimpleName)) *mockLocalDoguFetcher_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dogu.SimpleName
		if args[1] != nil {
			arg1 = args[1].(dogu.SimpleName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockLocalDoguFetcher_Enabled_Call) Return(b bool, err error) *mockLocalDoguFetcher_Enabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockLocalDoguFetcher_Enabled_Call) RunAndReturn(run func(ctx context.Context, doguName dogu.SimpleName) (bool, error)) *mockLocalDoguFetcher_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// FetchForResource provides a mock function for the type mockLocalDoguFetcher
func (_mock *mockLocalDoguFetcher) FetchForResource(ctx context.Context, doguResource *v2.Dogu) (*core.Dogu, error) {
	ret := _mock.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for FetchForResource")
	}

	var r0 *core.Dogu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.Dogu) (*core.Dogu, error)); ok {
		return returnFunc(ctx, doguResource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.Dogu) *core.Dogu); ok {
		r0 = returnFunc(ctx, doguResource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v2.Dogu) error); ok {
		r1 = returnFunc(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockLocalDoguFetcher_FetchForResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchForResource'
type mockLocalDoguFetcher_FetchForResource_Call struct {
	*mock.Call
}

// FetchForResource is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *mockLocalDoguFetcher_Expecter) FetchForResource(ctx any, doguResource any) *mockLocalDoguFetcher_FetchForResource_Call {
	return &mockLocalDoguFetcher_FetchForResource_Call{Call: _e.mock.On("FetchForResource", ctx, doguResource)}
}

func (_c *mockLocalDoguFetcher_FetchForResource_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *mockLocalDoguFetcher_FetchForResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.Dogu
		if args[1] != nil {
			arg1 = args[1].(*v2.Dogu)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockLocalDoguFetcher_FetchForResource_Call) Return(dogu1 *core.Dogu, err error) *mockLocalDoguFetcher_FetchForResource_Call {
	_c.Call.Return(dogu1, err)
	return _c
}

func (_c *mockLocalDoguFetcher_FetchForResource_Call) RunAndReturn(run func(ctx context.Context, doguResource *v2.Dogu) (*core.Dogu, error)) *mockLocalDoguFetcher_FetchForResource_Call {
	_c.Call.Return(run)
	return _c
}

// FetchInstalled provides a mock function for the type mockLocalDoguFetcher
func (_mock *mockLocalDoguFetcher) FetchInstalled(ctx context.Context, doguName dogu.SimpleName) (*core.Dogu, error) {
	ret := _mock.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for FetchInstalled")
	}

	var r0 *core.Dogu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) (*core.Dogu, error)); ok {
		return returnFunc(ctx, doguName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) *core.Dogu); ok {
		r0 = returnFunc(ctx, doguName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dogu.SimpleName) error); ok {
		r1 = returnFunc(ctx, doguName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockLocalDoguFetcher_FetchInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchInstalled'
type mockLocalDoguFetcher_FetchInstalled_Call struct {
	*mock.Call
}

// FetchInstalled is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName dogu.SimpleName
func (_e *mockLocalDoguFetcher_Expecter) FetchInstalled(ctx any, doguName any) *mockLocalDoguFetcher_FetchInstalled_Call {
	return &mockLocalDoguFetcher_FetchInstalled_Call{Call: _e.mock.On("FetchInstalled", ctx, doguName)}
}

func (_c *mockLocalDoguFetcher_FetchInstalled_Call) Run(run func(ctx context.Context, doguName dogu.SimpleName)) *mockLocalDoguFetcher_FetchInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dogu.SimpleName
		if args[1] != nil {
			arg1 = args[1].(dogu.SimpleName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockLocalDoguFetcher_FetchInstalled_Call) Return(installedDogu *core.Dogu, err error) *mockLocalDoguFetcher_FetchInstalled_Call {
	_c.Call.Return(installedDogu, err)
	return _c
}

func (_c *mockLocalDoguFetcher_FetchInstalled_Call) RunAndReturn(run func(ctx context.Context, doguName dogu.SimpleName) (*core.Dogu, error)) *mockLocalDoguFetcher_FetchInstalled_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// ValidateDependencies provides a mock function for the type MockValidator
func (_mock *MockValidator) ValidateDependencies(ctx context.Context, dogu1 *core.Dogu) error {
	ret := _mock.Called(ctx, dogu1)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDependencies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.Dogu) error); ok {
		r0 = returnFunc(ctx, dogu1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_ValidateDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateDependencies'
type MockValidator_ValidateDependencies_Call struct {
	*mock.Call
}

// ValidateDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu1 *core.Dogu
func (_e *MockValidator_Expecter) ValidateDependencies(ctx any, dogu1 any) *MockValidator_ValidateDependencies_Call {
	return &MockValidator_ValidateDependencies_Call{Call: _e.mock.On("ValidateDependencies", ctx, dogu1)}
}

func (_c *MockValidator_ValidateDependencies_Call) Run(run func(ctx context.Context, dogu1 *core.Dogu)) *MockValidator_ValidateDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.Dogu
		if args[1] != nil {
			arg1 = args[1].(*core.Dogu)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockValidator_ValidateDependencies_Call) Return(err error) *MockValidator_ValidateDependencies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_ValidateDependencies_Call) RunAndReturn(run func(ctx context.Context, dogu1 *core.Dogu) error) *MockValidator_ValidateDependencies_Call {
	_c.Call.Return(run)
	return _c
}
