// Code generated by mockery v2.53.7. DO NOT EDIT.

package install

import (
	context "context"

	v3beta1 "github.com/cloudogu/k8s-dogu-lib/v3/api/v3beta1"
	mock "github.com/stretchr/testify/mock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockChartService is an autogenerated mock type for the ChartService type
type MockChartService struct {
	mock.Mock
}

type MockChartService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChartService) EXPECT() *MockChartService_Expecter {
	return &MockChartService_Expecter{mock: &_m.Mock}
}

// DoguMetaValues provides a mock function with given fields: ctx, doguResource
func (_m *MockChartService) DoguMetaValues(ctx context.Context, doguResource *v3beta1.Dogu) ([]byte, bool, error) {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for DoguMetaValues")
	}

	var r0 []byte
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu) ([]byte, bool, error)); ok {
		return rf(ctx, doguResource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu) []byte); ok {
		r0 = rf(ctx, doguResource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v3beta1.Dogu) bool); ok {
		r1 = rf(ctx, doguResource)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *v3beta1.Dogu) error); ok {
		r2 = rf(ctx, doguResource)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChartService_DoguMetaValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoguMetaValues'
type MockChartService_DoguMetaValues_Call struct {
	*mock.Call
}

// DoguMetaValues is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v3beta1.Dogu
func (_e *MockChartService_Expecter) DoguMetaValues(ctx interface{}, doguResource interface{}) *MockChartService_DoguMetaValues_Call {
	return &MockChartService_DoguMetaValues_Call{Call: _e.mock.On("DoguMetaValues", ctx, doguResource)}
}

func (_c *MockChartService_DoguMetaValues_Call) Run(run func(ctx context.Context, doguResource *v3beta1.Dogu)) *MockChartService_DoguMetaValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v3beta1.Dogu))
	})
	return _c
}

func (_c *MockChartService_DoguMetaValues_Call) Return(_a0 []byte, _a1 bool, _a2 error) *MockChartService_DoguMetaValues_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChartService_DoguMetaValues_Call) RunAndReturn(run func(context.Context, *v3beta1.Dogu) ([]byte, bool, error)) *MockChartService_DoguMetaValues_Call {
	_c.Call.Return(run)
	return _c
}

// Render provides a mock function with given fields: ctx, doguResource, values
func (_m *MockChartService) Render(ctx context.Context, doguResource *v3beta1.Dogu, values map[string]interface{}) ([]client.Object, error) {
	ret := _m.Called(ctx, doguResource, values)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 []client.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu, map[string]interface{}) ([]client.Object, error)); ok {
		return rf(ctx, doguResource, values)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu, map[string]interface{}) []client.Object); ok {
		r0 = rf(ctx, doguResource, values)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v3beta1.Dogu, map[string]interface{}) error); ok {
		r1 = rf(ctx, doguResource, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChartService_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockChartService_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v3beta1.Dogu
//   - values map[string]interface{}
func (_e *MockChartService_Expecter) Render(ctx interface{}, doguResource interface{}, values interface{}) *MockChartService_Render_Call {
	return &MockChartService_Render_Call{Call: _e.mock.On("Render", ctx, doguResource, values)}
}

func (_c *MockChartService_Render_Call) Run(run func(ctx context.Context, doguResource *v3beta1.Dogu, values map[string]interface{})) *MockChartService_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v3beta1.Dogu), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockChartService_Render_Call) Return(_a0 []client.Object, _a1 error) *MockChartService_Render_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChartService_Render_Call) RunAndReturn(run func(context.Context, *v3beta1.Dogu, map[string]interface{}) ([]client.Object, error)) *MockChartService_Render_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateValues provides a mock function with given fields: ctx, doguResource, values
func (_m *MockChartService) ValidateValues(ctx context.Context, doguResource *v3beta1.Dogu, values map[string]interface{}) error {
	ret := _m.Called(ctx, doguResource, values)

	if len(ret) == 0 {
		panic("no return value specified for ValidateValues")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu, map[string]interface{}) error); ok {
		r0 = rf(ctx, doguResource, values)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChartService_ValidateValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateValues'
type MockChartService_ValidateValues_Call struct {
	*mock.Call
}

// ValidateValues is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v3beta1.Dogu
//   - values map[string]interface{}
func (_e *MockChartService_Expecter) ValidateValues(ctx interface{}, doguResource interface{}, values interface{}) *MockChartService_ValidateValues_Call {
	return &MockChartService_ValidateValues_Call{Call: _e.mock.On("ValidateValues", ctx, doguResource, values)}
}

func (_c *MockChartService_ValidateValues_Call) Run(run func(ctx context.Context, doguResource *v3beta1.Dogu, values map[string]interface{})) *MockChartService_ValidateValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v3beta1.Dogu), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockChartService_ValidateValues_Call) Return(_a0 error) *MockChartService_ValidateValues_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChartService_ValidateValues_Call) RunAndReturn(run func(context.Context, *v3beta1.Dogu, map[string]interface{}) error) *MockChartService_ValidateValues_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChartService creates a new instance of MockChartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChartService {
	mock := &MockChartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
