// Code generated by mockery v2.53.7. DO NOT EDIT.

package install

import (
	context "context"

	doguv3 "github.com/cloudogu/dogu-lib/doguv3"
	mock "github.com/stretchr/testify/mock"
)

// MockDoguRegistryReader is an autogenerated mock type for the DoguRegistryReader type
type MockDoguRegistryReader struct {
	mock.Mock
}

type MockDoguRegistryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguRegistryReader) EXPECT() *MockDoguRegistryReader_Expecter {
	return &MockDoguRegistryReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, doguIdentifier
func (_m *MockDoguRegistryReader) Get(ctx context.Context, doguIdentifier doguv3.Identifier) (*doguv3.Dogu, error) {
	ret := _m.Called(ctx, doguIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *doguv3.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, doguv3.Identifier) (*doguv3.Dogu, error)); ok {
		return rf(ctx, doguIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, doguv3.Identifier) *doguv3.Dogu); ok {
		r0 = rf(ctx, doguIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*doguv3.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, doguv3.Identifier) error); ok {
		r1 = rf(ctx, doguIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguRegistryReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDoguRegistryReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - doguIdentifier doguv3.Identifier
func (_e *MockDoguRegistryReader_Expecter) Get(ctx interface{}, doguIdentifier interface{}) *MockDoguRegistryReader_Get_Call {
	return &MockDoguRegistryReader_Get_Call{Call: _e.mock.On("Get", ctx, doguIdentifier)}
}

func (_c *MockDoguRegistryReader_Get_Call) Run(run func(ctx context.Context, doguIdentifier doguv3.Identifier)) *MockDoguRegistryReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(doguv3.Identifier))
	})
	return _c
}

func (_c *MockDoguRegistryReader_Get_Call) Return(_a0 *doguv3.Dogu, _a1 error) *MockDoguRegistryReader_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguRegistryReader_Get_Call) RunAndReturn(run func(context.Context, doguv3.Identifier) (*doguv3.Dogu, error)) *MockDoguRegistryReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguRegistryReader creates a new instance of MockDoguRegistryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguRegistryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguRegistryReader {
	mock := &MockDoguRegistryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
