// Code generated by mockery v2.53.7. DO NOT EDIT.

package install

import (
	context "context"

	v3beta1 "github.com/cloudogu/k8s-dogu-lib/v3/api/v3beta1"
	values "github.com/cloudogu/k8s-dogu-operator/v3/internal/dogu/values"
	mock "github.com/stretchr/testify/mock"
)

// MockAssembler is an autogenerated mock type for the Assembler type
type MockAssembler struct {
	mock.Mock
}

type MockAssembler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssembler) EXPECT() *MockAssembler_Expecter {
	return &MockAssembler_Expecter{mock: &_m.Mock}
}

// Assemble provides a mock function with given fields: ctx, cr, valuesMeta
func (_m *MockAssembler) Assemble(ctx context.Context, cr *v3beta1.Dogu, valuesMeta []byte) (values.Values, error) {
	ret := _m.Called(ctx, cr, valuesMeta)

	if len(ret) == 0 {
		panic("no return value specified for Assemble")
	}

	var r0 values.Values
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu, []byte) (values.Values, error)); ok {
		return rf(ctx, cr, valuesMeta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu, []byte) values.Values); ok {
		r0 = rf(ctx, cr, valuesMeta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(values.Values)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v3beta1.Dogu, []byte) error); ok {
		r1 = rf(ctx, cr, valuesMeta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAssembler_Assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assemble'
type MockAssembler_Assemble_Call struct {
	*mock.Call
}

// Assemble is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *v3beta1.Dogu
//   - valuesMeta []byte
func (_e *MockAssembler_Expecter) Assemble(ctx interface{}, cr interface{}, valuesMeta interface{}) *MockAssembler_Assemble_Call {
	return &MockAssembler_Assemble_Call{Call: _e.mock.On("Assemble", ctx, cr, valuesMeta)}
}

func (_c *MockAssembler_Assemble_Call) Run(run func(ctx context.Context, cr *v3beta1.Dogu, valuesMeta []byte)) *MockAssembler_Assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v3beta1.Dogu), args[2].([]byte))
	})
	return _c
}

func (_c *MockAssembler_Assemble_Call) Return(_a0 values.Values, _a1 error) *MockAssembler_Assemble_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAssembler_Assemble_Call) RunAndReturn(run func(context.Context, *v3beta1.Dogu, []byte) (values.Values, error)) *MockAssembler_Assemble_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAssembler creates a new instance of MockAssembler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssembler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssembler {
	mock := &MockAssembler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
