// Code generated by mockery v2.53.3. DO NOT EDIT.

package postinstall

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v1 "k8s.io/client-go/kubernetes/typed/apps/v1"
)

// mockAppV1Interface is an autogenerated mock type for the appV1Interface type
type mockAppV1Interface struct {
	mock.Mock
}

type mockAppV1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAppV1Interface) EXPECT() *mockAppV1Interface_Expecter {
	return &mockAppV1Interface_Expecter{mock: &_m.Mock}
}

// ControllerRevisions provides a mock function with given fields: namespace
func (_m *mockAppV1Interface) ControllerRevisions(namespace string) v1.ControllerRevisionInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ControllerRevisions")
	}

	var r0 v1.ControllerRevisionInterface
	if rf, ok := ret.Get(0).(func(string) v1.ControllerRevisionInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ControllerRevisionInterface)
		}
	}

	return r0
}

// mockAppV1Interface_ControllerRevisions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ControllerRevisions'
type mockAppV1Interface_ControllerRevisions_Call struct {
	*mock.Call
}

// ControllerRevisions is a helper method to define mock.On call
//   - namespace string
func (_e *mockAppV1Interface_Expecter) ControllerRevisions(namespace interface{}) *mockAppV1Interface_ControllerRevisions_Call {
	return &mockAppV1Interface_ControllerRevisions_Call{Call: _e.mock.On("ControllerRevisions", namespace)}
}

func (_c *mockAppV1Interface_ControllerRevisions_Call) Run(run func(namespace string)) *mockAppV1Interface_ControllerRevisions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockAppV1Interface_ControllerRevisions_Call) Return(_a0 v1.ControllerRevisionInterface) *mockAppV1Interface_ControllerRevisions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAppV1Interface_ControllerRevisions_Call) RunAndReturn(run func(string) v1.ControllerRevisionInterface) *mockAppV1Interface_ControllerRevisions_Call {
	_c.Call.Return(run)
	return _c
}

// DaemonSets provides a mock function with given fields: namespace
func (_m *mockAppV1Interface) DaemonSets(namespace string) v1.DaemonSetInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for DaemonSets")
	}

	var r0 v1.DaemonSetInterface
	if rf, ok := ret.Get(0).(func(string) v1.DaemonSetInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.DaemonSetInterface)
		}
	}

	return r0
}

// mockAppV1Interface_DaemonSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DaemonSets'
type mockAppV1Interface_DaemonSets_Call struct {
	*mock.Call
}

// DaemonSets is a helper method to define mock.On call
//   - namespace string
func (_e *mockAppV1Interface_Expecter) DaemonSets(namespace interface{}) *mockAppV1Interface_DaemonSets_Call {
	return &mockAppV1Interface_DaemonSets_Call{Call: _e.mock.On("DaemonSets", namespace)}
}

func (_c *mockAppV1Interface_DaemonSets_Call) Run(run func(namespace string)) *mockAppV1Interface_DaemonSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockAppV1Interface_DaemonSets_Call) Return(_a0 v1.DaemonSetInterface) *mockAppV1Interface_DaemonSets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAppV1Interface_DaemonSets_Call) RunAndReturn(run func(string) v1.DaemonSetInterface) *mockAppV1Interface_DaemonSets_Call {
	_c.Call.Return(run)
	return _c
}

// Deployments provides a mock function with given fields: namespace
func (_m *mockAppV1Interface) Deployments(namespace string) v1.DeploymentInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Deployments")
	}

	var r0 v1.DeploymentInterface
	if rf, ok := ret.Get(0).(func(string) v1.DeploymentInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.DeploymentInterface)
		}
	}

	return r0
}

// mockAppV1Interface_Deployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployments'
type mockAppV1Interface_Deployments_Call struct {
	*mock.Call
}

// Deployments is a helper method to define mock.On call
//   - namespace string
func (_e *mockAppV1Interface_Expecter) Deployments(namespace interface{}) *mockAppV1Interface_Deployments_Call {
	return &mockAppV1Interface_Deployments_Call{Call: _e.mock.On("Deployments", namespace)}
}

func (_c *mockAppV1Interface_Deployments_Call) Run(run func(namespace string)) *mockAppV1Interface_Deployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockAppV1Interface_Deployments_Call) Return(_a0 v1.DeploymentInterface) *mockAppV1Interface_Deployments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAppV1Interface_Deployments_Call) RunAndReturn(run func(string) v1.DeploymentInterface) *mockAppV1Interface_Deployments_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function with no fields
func (_m *mockAppV1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// mockAppV1Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type mockAppV1Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *mockAppV1Interface_Expecter) RESTClient() *mockAppV1Interface_RESTClient_Call {
	return &mockAppV1Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *mockAppV1Interface_RESTClient_Call) Run(run func()) *mockAppV1Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockAppV1Interface_RESTClient_Call) Return(_a0 rest.Interface) *mockAppV1Interface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAppV1Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *mockAppV1Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// ReplicaSets provides a mock function with given fields: namespace
func (_m *mockAppV1Interface) ReplicaSets(namespace string) v1.ReplicaSetInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ReplicaSets")
	}

	var r0 v1.ReplicaSetInterface
	if rf, ok := ret.Get(0).(func(string) v1.ReplicaSetInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ReplicaSetInterface)
		}
	}

	return r0
}

// mockAppV1Interface_ReplicaSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplicaSets'
type mockAppV1Interface_ReplicaSets_Call struct {
	*mock.Call
}

// ReplicaSets is a helper method to define mock.On call
//   - namespace string
func (_e *mockAppV1Interface_Expecter) ReplicaSets(namespace interface{}) *mockAppV1Interface_ReplicaSets_Call {
	return &mockAppV1Interface_ReplicaSets_Call{Call: _e.mock.On("ReplicaSets", namespace)}
}

func (_c *mockAppV1Interface_ReplicaSets_Call) Run(run func(namespace string)) *mockAppV1Interface_ReplicaSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockAppV1Interface_ReplicaSets_Call) Return(_a0 v1.ReplicaSetInterface) *mockAppV1Interface_ReplicaSets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAppV1Interface_ReplicaSets_Call) RunAndReturn(run func(string) v1.ReplicaSetInterface) *mockAppV1Interface_ReplicaSets_Call {
	_c.Call.Return(run)
	return _c
}

// StatefulSets provides a mock function with given fields: namespace
func (_m *mockAppV1Interface) StatefulSets(namespace string) v1.StatefulSetInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for StatefulSets")
	}

	var r0 v1.StatefulSetInterface
	if rf, ok := ret.Get(0).(func(string) v1.StatefulSetInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.StatefulSetInterface)
		}
	}

	return r0
}

// mockAppV1Interface_StatefulSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatefulSets'
type mockAppV1Interface_StatefulSets_Call struct {
	*mock.Call
}

// StatefulSets is a helper method to define mock.On call
//   - namespace string
func (_e *mockAppV1Interface_Expecter) StatefulSets(namespace interface{}) *mockAppV1Interface_StatefulSets_Call {
	return &mockAppV1Interface_StatefulSets_Call{Call: _e.mock.On("StatefulSets", namespace)}
}

func (_c *mockAppV1Interface_StatefulSets_Call) Run(run func(namespace string)) *mockAppV1Interface_StatefulSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockAppV1Interface_StatefulSets_Call) Return(_a0 v1.StatefulSetInterface) *mockAppV1Interface_StatefulSets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAppV1Interface_StatefulSets_Call) RunAndReturn(run func(string) v1.StatefulSetInterface) *mockAppV1Interface_StatefulSets_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAppV1Interface creates a new instance of mockAppV1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAppV1Interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAppV1Interface {
	mock := &mockAppV1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
