// Code generated by mockery v2.53.6. DO NOT EDIT.

package authregistration

import (
	context "context"

	dogu "github.com/cloudogu/ces-commons-lib/dogu"
	core "github.com/cloudogu/cesapp-lib/core"

	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// EnsureAuthRegistration provides a mock function with given fields: ctx, _a1
func (_m *MockManager) EnsureAuthRegistration(ctx context.Context, _a1 *core.Dogu) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EnsureAuthRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.Dogu) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_EnsureAuthRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureAuthRegistration'
type MockManager_EnsureAuthRegistration_Call struct {
	*mock.Call
}

// EnsureAuthRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *core.Dogu
func (_e *MockManager_Expecter) EnsureAuthRegistration(ctx interface{}, _a1 interface{}) *MockManager_EnsureAuthRegistration_Call {
	return &MockManager_EnsureAuthRegistration_Call{Call: _e.mock.On("EnsureAuthRegistration", ctx, _a1)}
}

func (_c *MockManager_EnsureAuthRegistration_Call) Run(run func(ctx context.Context, _a1 *core.Dogu)) *MockManager_EnsureAuthRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.Dogu))
	})
	return _c
}

func (_c *MockManager_EnsureAuthRegistration_Call) Return(_a0 error) *MockManager_EnsureAuthRegistration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_EnsureAuthRegistration_Call) RunAndReturn(run func(context.Context, *core.Dogu) error) *MockManager_EnsureAuthRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAuthRegistration provides a mock function with given fields: ctx, doguName
func (_m *MockManager) RemoveAuthRegistration(ctx context.Context, doguName dogu.SimpleName) error {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAuthRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleName) error); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_RemoveAuthRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAuthRegistration'
type MockManager_RemoveAuthRegistration_Call struct {
	*mock.Call
}

// RemoveAuthRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName dogu.SimpleName
func (_e *MockManager_Expecter) RemoveAuthRegistration(ctx interface{}, doguName interface{}) *MockManager_RemoveAuthRegistration_Call {
	return &MockManager_RemoveAuthRegistration_Call{Call: _e.mock.On("RemoveAuthRegistration", ctx, doguName)}
}

func (_c *MockManager_RemoveAuthRegistration_Call) Run(run func(ctx context.Context, doguName dogu.SimpleName)) *MockManager_RemoveAuthRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dogu.SimpleName))
	})
	return _c
}

func (_c *MockManager_RemoveAuthRegistration_Call) Return(_a0 error) *MockManager_RemoveAuthRegistration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_RemoveAuthRegistration_Call) RunAndReturn(run func(context.Context, dogu.SimpleName) error) *MockManager_RemoveAuthRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
