// Code generated by mockery v2.53.6. DO NOT EDIT.

package authregistration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "github.com/cloudogu/k8s-auth-registration-lib/api/v1"
)

// mockAuthRegistrationClient is an autogenerated mock type for the authRegistrationClient type
type mockAuthRegistrationClient struct {
	mock.Mock
}

type mockAuthRegistrationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuthRegistrationClient) EXPECT() *mockAuthRegistrationClient_Expecter {
	return &mockAuthRegistrationClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, authRegistration, opts
func (_m *mockAuthRegistrationClient) Create(ctx context.Context, authRegistration *v1.AuthRegistration, opts metav1.CreateOptions) (*v1.AuthRegistration, error) {
	ret := _m.Called(ctx, authRegistration, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.AuthRegistration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, metav1.CreateOptions) (*v1.AuthRegistration, error)); ok {
		return rf(ctx, authRegistration, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, metav1.CreateOptions) *v1.AuthRegistration); ok {
		r0 = rf(ctx, authRegistration, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AuthRegistration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.AuthRegistration, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, authRegistration, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAuthRegistrationClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockAuthRegistrationClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
//   - opts metav1.CreateOptions
func (_e *mockAuthRegistrationClient_Expecter) Create(ctx interface{}, authRegistration interface{}, opts interface{}) *mockAuthRegistrationClient_Create_Call {
	return &mockAuthRegistrationClient_Create_Call{Call: _e.mock.On("Create", ctx, authRegistration, opts)}
}

func (_c *mockAuthRegistrationClient_Create_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration, opts metav1.CreateOptions)) *mockAuthRegistrationClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockAuthRegistrationClient_Create_Call) Return(_a0 *v1.AuthRegistration, _a1 error) *mockAuthRegistrationClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAuthRegistrationClient_Create_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration, metav1.CreateOptions) (*v1.AuthRegistration, error)) *mockAuthRegistrationClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockAuthRegistrationClient) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockAuthRegistrationClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockAuthRegistrationClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockAuthRegistrationClient_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockAuthRegistrationClient_Delete_Call {
	return &mockAuthRegistrationClient_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockAuthRegistrationClient_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockAuthRegistrationClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockAuthRegistrationClient_Delete_Call) Return(_a0 error) *mockAuthRegistrationClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAuthRegistrationClient_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockAuthRegistrationClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockAuthRegistrationClient) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AuthRegistration, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.AuthRegistration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*v1.AuthRegistration, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1.AuthRegistration); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AuthRegistration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAuthRegistrationClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockAuthRegistrationClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockAuthRegistrationClient_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockAuthRegistrationClient_Get_Call {
	return &mockAuthRegistrationClient_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockAuthRegistrationClient_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockAuthRegistrationClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockAuthRegistrationClient_Get_Call) Return(_a0 *v1.AuthRegistration, _a1 error) *mockAuthRegistrationClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAuthRegistrationClient_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*v1.AuthRegistration, error)) *mockAuthRegistrationClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, authRegistration, opts
func (_m *mockAuthRegistrationClient) Update(ctx context.Context, authRegistration *v1.AuthRegistration, opts metav1.UpdateOptions) (*v1.AuthRegistration, error) {
	ret := _m.Called(ctx, authRegistration, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.AuthRegistration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, metav1.UpdateOptions) (*v1.AuthRegistration, error)); ok {
		return rf(ctx, authRegistration, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, metav1.UpdateOptions) *v1.AuthRegistration); ok {
		r0 = rf(ctx, authRegistration, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AuthRegistration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.AuthRegistration, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, authRegistration, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAuthRegistrationClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockAuthRegistrationClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
//   - opts metav1.UpdateOptions
func (_e *mockAuthRegistrationClient_Expecter) Update(ctx interface{}, authRegistration interface{}, opts interface{}) *mockAuthRegistrationClient_Update_Call {
	return &mockAuthRegistrationClient_Update_Call{Call: _e.mock.On("Update", ctx, authRegistration, opts)}
}

func (_c *mockAuthRegistrationClient_Update_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration, opts metav1.UpdateOptions)) *mockAuthRegistrationClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockAuthRegistrationClient_Update_Call) Return(_a0 *v1.AuthRegistration, _a1 error) *mockAuthRegistrationClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAuthRegistrationClient_Update_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration, metav1.UpdateOptions) (*v1.AuthRegistration, error)) *mockAuthRegistrationClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAuthRegistrationClient creates a new instance of mockAuthRegistrationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuthRegistrationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuthRegistrationClient {
	mock := &mockAuthRegistrationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
