// Code generated by mockery v2.53.5. DO NOT EDIT.

package health

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthShutdownHandler is an autogenerated mock type for the HealthShutdownHandler type
type MockHealthShutdownHandler struct {
	mock.Mock
}

type MockHealthShutdownHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthShutdownHandler) EXPECT() *MockHealthShutdownHandler_Expecter {
	return &MockHealthShutdownHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx
func (_m *MockHealthShutdownHandler) Handle(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthShutdownHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockHealthShutdownHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthShutdownHandler_Expecter) Handle(ctx interface{}) *MockHealthShutdownHandler_Handle_Call {
	return &MockHealthShutdownHandler_Handle_Call{Call: _e.mock.On("Handle", ctx)}
}

func (_c *MockHealthShutdownHandler_Handle_Call) Run(run func(ctx context.Context)) *MockHealthShutdownHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthShutdownHandler_Handle_Call) Return(_a0 error) *MockHealthShutdownHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthShutdownHandler_Handle_Call) RunAndReturn(run func(context.Context) error) *MockHealthShutdownHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthShutdownHandler creates a new instance of MockHealthShutdownHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthShutdownHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthShutdownHandler {
	mock := &MockHealthShutdownHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
