// Code generated by mockery v2.53.6. DO NOT EDIT.

package health

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	v2 "github.com/cloudogu/k8s-dogu-lib/v3/client/typed/api/v2"
)

// mockDoguV2Interface is an autogenerated mock type for the doguV2Interface type
type mockDoguV2Interface struct {
	mock.Mock
}

type mockDoguV2Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguV2Interface) EXPECT() *mockDoguV2Interface_Expecter {
	return &mockDoguV2Interface_Expecter{mock: &_m.Mock}
}

// DoguRestarts provides a mock function with given fields: namespace
func (_m *mockDoguV2Interface) DoguRestarts(namespace string) v2.DoguRestartInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for DoguRestarts")
	}

	var r0 v2.DoguRestartInterface
	if rf, ok := ret.Get(0).(func(string) v2.DoguRestartInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2.DoguRestartInterface)
		}
	}

	return r0
}

// mockDoguV2Interface_DoguRestarts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoguRestarts'
type mockDoguV2Interface_DoguRestarts_Call struct {
	*mock.Call
}

// DoguRestarts is a helper method to define mock.On call
//   - namespace string
func (_e *mockDoguV2Interface_Expecter) DoguRestarts(namespace interface{}) *mockDoguV2Interface_DoguRestarts_Call {
	return &mockDoguV2Interface_DoguRestarts_Call{Call: _e.mock.On("DoguRestarts", namespace)}
}

func (_c *mockDoguV2Interface_DoguRestarts_Call) Run(run func(namespace string)) *mockDoguV2Interface_DoguRestarts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockDoguV2Interface_DoguRestarts_Call) Return(_a0 v2.DoguRestartInterface) *mockDoguV2Interface_DoguRestarts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguV2Interface_DoguRestarts_Call) RunAndReturn(run func(string) v2.DoguRestartInterface) *mockDoguV2Interface_DoguRestarts_Call {
	_c.Call.Return(run)
	return _c
}

// Dogus provides a mock function with given fields: namespace
func (_m *mockDoguV2Interface) Dogus(namespace string) v2.DoguInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Dogus")
	}

	var r0 v2.DoguInterface
	if rf, ok := ret.Get(0).(func(string) v2.DoguInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2.DoguInterface)
		}
	}

	return r0
}

// mockDoguV2Interface_Dogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dogus'
type mockDoguV2Interface_Dogus_Call struct {
	*mock.Call
}

// Dogus is a helper method to define mock.On call
//   - namespace string
func (_e *mockDoguV2Interface_Expecter) Dogus(namespace interface{}) *mockDoguV2Interface_Dogus_Call {
	return &mockDoguV2Interface_Dogus_Call{Call: _e.mock.On("Dogus", namespace)}
}

func (_c *mockDoguV2Interface_Dogus_Call) Run(run func(namespace string)) *mockDoguV2Interface_Dogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockDoguV2Interface_Dogus_Call) Return(_a0 v2.DoguInterface) *mockDoguV2Interface_Dogus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguV2Interface_Dogus_Call) RunAndReturn(run func(string) v2.DoguInterface) *mockDoguV2Interface_Dogus_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function with no fields
func (_m *mockDoguV2Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// mockDoguV2Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type mockDoguV2Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *mockDoguV2Interface_Expecter) RESTClient() *mockDoguV2Interface_RESTClient_Call {
	return &mockDoguV2Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *mockDoguV2Interface_RESTClient_Call) Run(run func()) *mockDoguV2Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDoguV2Interface_RESTClient_Call) Return(_a0 rest.Interface) *mockDoguV2Interface_RESTClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguV2Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *mockDoguV2Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguV2Interface creates a new instance of mockDoguV2Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguV2Interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguV2Interface {
	mock := &mockDoguV2Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
