// Code generated by mockery v2.53.2. DO NOT EDIT.

package health

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguRecursiveHealthChecker is an autogenerated mock type for the doguRecursiveHealthChecker type
type mockDoguRecursiveHealthChecker struct {
	mock.Mock
}

type mockDoguRecursiveHealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguRecursiveHealthChecker) EXPECT() *mockDoguRecursiveHealthChecker_Expecter {
	return &mockDoguRecursiveHealthChecker_Expecter{mock: &_m.Mock}
}

// CheckDependenciesRecursive provides a mock function with given fields: ctx, fromDogu, namespace
func (_m *mockDoguRecursiveHealthChecker) CheckDependenciesRecursive(ctx context.Context, fromDogu *core.Dogu, namespace string) error {
	ret := _m.Called(ctx, fromDogu, namespace)

	if len(ret) == 0 {
		panic("no return value specified for CheckDependenciesRecursive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.Dogu, string) error); ok {
		r0 = rf(ctx, fromDogu, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckDependenciesRecursive'
type mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call struct {
	*mock.Call
}

// CheckDependenciesRecursive is a helper method to define mock.On call
//   - ctx context.Context
//   - fromDogu *core.Dogu
//   - namespace string
func (_e *mockDoguRecursiveHealthChecker_Expecter) CheckDependenciesRecursive(ctx interface{}, fromDogu interface{}, namespace interface{}) *mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call {
	return &mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call{Call: _e.mock.On("CheckDependenciesRecursive", ctx, fromDogu, namespace)}
}

func (_c *mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call) Run(run func(ctx context.Context, fromDogu *core.Dogu, namespace string)) *mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.Dogu), args[2].(string))
	})
	return _c
}

func (_c *mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call) Return(_a0 error) *mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call) RunAndReturn(run func(context.Context, *core.Dogu, string) error) *mockDoguRecursiveHealthChecker_CheckDependenciesRecursive_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguRecursiveHealthChecker creates a new instance of mockDoguRecursiveHealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguRecursiveHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguRecursiveHealthChecker {
	mock := &mockDoguRecursiveHealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
