apiVersion: k8s.cloudogu.com/v2
kind: Dogu
metadata:
  name: nexus
  labels:
    app: ces
spec:
  name: official/nexus
  version: 3.70.2-5
  resources:
    dataVolumeSize: 5Gi
  additionalIngressAnnotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"