apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: nexus
  annotations:
    test: dev
  labels:
    dogu.name: nexus
    dogu.version: 3.40.1-2
    app: ces
spec:
  name: official/nexus
  version: 3.40.1-2