apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: plantuml
  annotations:
    test: dev
  labels:
    dogu.name: plantuml
    dogu.version: 2022.4-1
    app: ces
spec:
  name: official/plantuml
  version: 2022.4-1