apiVersion: k8s.cloudogu.com/v2
kind: Dogu
metadata:
  name: scm
  labels:
    app: ces
spec:
  name: official/scm
  version: 3.4.1-3
  additionalIngressAnnotations:
    # set a proxy-body-size value of "0" to enable requests of any size
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"