apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: scm
  annotations:
    test: dev
  labels:
    dogu.name: scm
    dogu.version: 2.38.1-1
    app: ces
spec:
  name: testing/scm
  version: 2.38.1-1