apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: sonar
  annotations:
    test: dev
  labels:
    dogu.name: sonar
    dogu.version: 8.9.8-2
    app: ces
spec:
  name: official/sonar
  version: 8.9.8-2