apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: swaggerui
  annotations:
    test: dev
  labels:
    dogu.name: swaggerui
    dogu.version: 4.9.0-1
    app: ces
spec:
  name: official/swaggerui
  version: 4.9.0-1