apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: usermgt
  annotations:
    test: dev
  labels:
    dogu.name: usermgt
    app: ces
spec:
  name: official/usermgt
  version: 1.7.0-1
  resources:
    dataVolumeSize: "6Gi"