apiVersion: v1
values:
  images:
    doguOperator: cloudogu/k8s-dogu-operator:3.2.0
    chownInitImage: busybox:1.36
patches:
  values.yaml:
    additionalImages:
      chownInitImage: "{{ .images.chownInitImage }}"
    controllerManager:
      image:
        registry: "{{ registryFrom .images.doguOperator }}"
        repository: "{{ repositoryFrom .images.doguOperator }}"
        tag: "{{ tagFrom .images.doguOperator }}"
