apiVersion: v1

values:
  images:
    dogu-operator: cloudogu/k8s-dogu-operator:0.38.0
    kube-rbac-proxy: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1

patches:
  values.yaml:
    additionalImages:
    kubeRbacProxy:
      image:
        repository: "{{ registryFrom .images.kube-rbac-proxy }}/{{ repositoryFrom .images.kube-rbac-proxy }}"
        tag: "{{ tagFrom .images.kube-rbac-proxy }}"
    controllerManager:
      image:
        repository: "{{ registryFrom .images.dogu-operator }}/{{ repositoryFrom .images.dogu-operator }}"
        tag: "{{ tagFrom .images.dogu-operator }}"