apiVersion: v1
values:
  images:
    doguOperator: cloudogu/k8s-dogu-operator:0.39.1
    kubeRbacProxy: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
    chownInitImage: busybox:1.36
patches:
  values.yaml:
    additionalImages:
      chownInitImage: "{{ .images.chownInitImage }}"
    kubeRbacProxy:
      image:
        repository: "{{ registryFrom .images.kubeRbacProxy }}/{{ repositoryFrom .images.kubeRbacProxy }}"
        tag: "{{ tagFrom .images.kubeRbacProxy }}"
    controllerManager:
      image:
        repository: "{{ registryFrom .images.doguOperator }}/{{ repositoryFrom .images.doguOperator }}"
        tag: "{{ tagFrom .images.doguOperator }}"
