apiVersion: v1
values:
  images:
    doguOperator: cloudogu/k8s-dogu-operator:3.3.0
    chownInitImage: busybox:1.36
    exporterImage: registry.cloudogu.com/k8s/rsync-sidecar:1.0.0
patches:
  values.yaml:
    additionalImages:
      chownInitImage: "{{ .images.chownInitImage }}"
      exporterImage: "{{ .images.exporterImage }}"
    controllerManager:
      image:
        registry: "{{ registryFrom .images.doguOperator }}"
        repository: "{{ repositoryFrom .images.doguOperator }}"
        tag: "{{ tagFrom .images.doguOperator }}"
