apiVersion: v2
values:
  images:
    doguOperator: cloudogu/k8s-dogu-operator:2.2.1
    kubeRbacProxy: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
    chownInitImage: busybox:1.36
patches:
  values.yaml:
    additionalImages:
      chownInitImage: "{{ .images.chownInitImage }}"
    kubeRbacProxy:
      image:
        registry: "{{ registryFrom .images.kubeRbacProxy }}"
        repository: "{{ repositoryFrom .images.kubeRbacProxy }}"
        tag: "{{ tagFrom .images.kubeRbacProxy }}"
    controllerManager:
      image:
        registry: "{{ registryFrom .images.doguOperator }}"
        repository: "{{ repositoryFrom .images.doguOperator }}"
        tag: "{{ tagFrom .images.doguOperator }}"
