networkPolicies:
  enabled: true
global:
  imagePullSecrets:
    - name: "ces-container-registries"
  networkPolicies:
    enabled: true
additionalImages:
  # chownInitImage will be used to change file permissions on writeable dogu volumes
  chownInitImage: busybox:1.36
  # exporterImage will be used as sidecar container if the export-mode of a dogu is active
  exporterImage: registry.cloudogu.com/k8s/rsync-sidecar:1.1.0
  # additionalMountsInitContainerImage will be used as init container if the dogu mounts additional data
  additionalMountsInitContainerImage: cloudogu/dogu-additional-mounts-init:0.1.2
controllerManager:
  image:
    registry: docker.io
    repository: cloudogu/k8s-dogu-operator
    tag: 3.12.0
  imagePullPolicy: IfNotPresent
  env:
    logLevel: debug
    stage: development
    doguStartupProbeTimeout: 1
    doguRestartSuccessfulHistoryLimit: 3
    doguRestartFailedHistoryLimit: 3
    doguRestartGarbageCollectionDisabled: false
    doguDescriptorMaxRetries: 20
    getServiceAccountPodMaxRetries: 5
  resourceLimits:
    memory: 105M
  resourceRequests:
    cpu: 15m
    memory: 105M
