networkPolicies:
  enabled: true
global:
  imagePullSecrets:
    - name: "ces-container-registries"
  networkPolicies:
    enabled: true
additionalImages:
  # chownInitImage will be used to change file permissions on writeable dogu volumes
  chownInitImage: busybox:1.36
controllerManager:
  image:
    registry: docker.io
    repository: cloudogu/k8s-dogu-operator
    tag: 3.0.3
  imagePullPolicy: IfNotPresent
  env:
    logLevel: debug
    stage: development
    doguStartupProbeTimeout: 1
    doguRestartSuccessfulHistoryLimit: 3
    doguRestartFailedHistoryLimit: 3
    doguRestartGarbageCollectionDisabled: false
    doguDescriptorMaxRetries: 20
    getServiceAccountPodMaxRetries: 5
  resourceLimits:
    cpu: 500m
    memory: 128Mi
  resourceRequests:
    cpu: 10m
    memory: 64Mi
kubeRbacProxy:
  image:
    registry: gcr.io
    repository: kubebuilder/kube-rbac-proxy
    tag: v0.14.1
  resourceLimits:
    cpu: 500m
    memory: 128Mi
  resourceRequests:
    cpu: 5m
    memory: 64Mi
