additionalImages:
  # chownInitImage will be used to change file permissions on writeable dogu volumes
  chownInitImage: busybox:1.36
controllerManager:
  image:
    repository: europe-west3-docker.pkg.dev/ces-coder-workspaces/ces-test-docker-helm-repo/images/k8s-dogu-operator
    tag: 1.2.0-test
  imagePullPolicy: Always
  env:
    logLevel: debug
    stage: development
    doguStartupProbeTimeout: 1
    doguRestartSuccessfulHistoryLimit: 3
    doguRestartFailedHistoryLimit: 3
    doguRestartGarbageCollectionDisabled: false
  resourceLimits:
    cpu: 500m
    memory: 128Mi
  resourceRequests:
    cpu: 10m
    memory: 64Mi
kubeRbacProxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.14.1
  resourceLimits:
    cpu: 500m
    memory: 128Mi
  resourceRequests:
    cpu: 5m
    memory: 64Mi
