additionalImages:
  # chownInitImage will be used to change file permissions on writeable dogu volumes
  chownInitImage: busybox:1.36
controllerManager:
  image:
    repository: cloudogu/k8s-dogu-operator
    tag: 0.39.0
  imagePullPolicy: IfNotPresent
  env:
    logLevel: debug
    stage: development
  resourceLimits:
    cpu: 500m
    memory: 128Mi
  resourceRequests:
    cpu: 10m
    memory: 64Mi
kubeRbacProxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.14.1
  resourceLimits:
    cpu: 500m
    memory: 128Mi
  resourceRequests:
    cpu: 5m
    memory: 64Mi
