// Code generated by mockery v2.46.2. DO NOT EDIT.

package resource

import (
	context "context"

	v2 "github.com/cloudogu/k8s-dogu-operator/v2/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// MockDoguSecretHandler is an autogenerated mock type for the DoguSecretHandler type
type MockDoguSecretHandler struct {
	mock.Mock
}

type MockDoguSecretHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguSecretHandler) EXPECT() *MockDoguSecretHandler_Expecter {
	return &MockDoguSecretHandler_Expecter{mock: &_m.Mock}
}

// WriteDoguSecretsToRegistry provides a mock function with given fields: ctx, doguResource
func (_m *MockDoguSecretHandler) WriteDoguSecretsToRegistry(ctx context.Context, doguResource *v2.Dogu) error {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for WriteDoguSecretsToRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) error); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteDoguSecretsToRegistry'
type MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call struct {
	*mock.Call
}

// WriteDoguSecretsToRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *MockDoguSecretHandler_Expecter) WriteDoguSecretsToRegistry(ctx interface{}, doguResource interface{}) *MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call {
	return &MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call{Call: _e.mock.On("WriteDoguSecretsToRegistry", ctx, doguResource)}
}

func (_c *MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call) Return(_a0 error) *MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call) RunAndReturn(run func(context.Context, *v2.Dogu) error) *MockDoguSecretHandler_WriteDoguSecretsToRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguSecretHandler creates a new instance of MockDoguSecretHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguSecretHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguSecretHandler {
	mock := &MockDoguSecretHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
