// Code generated by mockery v2.46.2. DO NOT EDIT.

package exec

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	remotecommand "k8s.io/client-go/tools/remotecommand"
)

// MockRemoteExecutor is an autogenerated mock type for the RemoteExecutor type
type MockRemoteExecutor struct {
	mock.Mock
}

type MockRemoteExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemoteExecutor) EXPECT() *MockRemoteExecutor_Expecter {
	return &MockRemoteExecutor_Expecter{mock: &_m.Mock}
}

// Stream provides a mock function with given fields: options
func (_m *MockRemoteExecutor) Stream(options remotecommand.StreamOptions) error {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(remotecommand.StreamOptions) error); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemoteExecutor_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type MockRemoteExecutor_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - options remotecommand.StreamOptions
func (_e *MockRemoteExecutor_Expecter) Stream(options interface{}) *MockRemoteExecutor_Stream_Call {
	return &MockRemoteExecutor_Stream_Call{Call: _e.mock.On("Stream", options)}
}

func (_c *MockRemoteExecutor_Stream_Call) Run(run func(options remotecommand.StreamOptions)) *MockRemoteExecutor_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(remotecommand.StreamOptions))
	})
	return _c
}

func (_c *MockRemoteExecutor_Stream_Call) Return(_a0 error) *MockRemoteExecutor_Stream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemoteExecutor_Stream_Call) RunAndReturn(run func(remotecommand.StreamOptions) error) *MockRemoteExecutor_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// StreamWithContext provides a mock function with given fields: ctx, options
func (_m *MockRemoteExecutor) StreamWithContext(ctx context.Context, options remotecommand.StreamOptions) error {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for StreamWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, remotecommand.StreamOptions) error); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRemoteExecutor_StreamWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamWithContext'
type MockRemoteExecutor_StreamWithContext_Call struct {
	*mock.Call
}

// StreamWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - options remotecommand.StreamOptions
func (_e *MockRemoteExecutor_Expecter) StreamWithContext(ctx interface{}, options interface{}) *MockRemoteExecutor_StreamWithContext_Call {
	return &MockRemoteExecutor_StreamWithContext_Call{Call: _e.mock.On("StreamWithContext", ctx, options)}
}

func (_c *MockRemoteExecutor_StreamWithContext_Call) Run(run func(ctx context.Context, options remotecommand.StreamOptions)) *MockRemoteExecutor_StreamWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(remotecommand.StreamOptions))
	})
	return _c
}

func (_c *MockRemoteExecutor_StreamWithContext_Call) Return(_a0 error) *MockRemoteExecutor_StreamWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRemoteExecutor_StreamWithContext_Call) RunAndReturn(run func(context.Context, remotecommand.StreamOptions) error) *MockRemoteExecutor_StreamWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRemoteExecutor creates a new instance of MockRemoteExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoteExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoteExecutor {
	mock := &MockRemoteExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
