Dogu Controller Flow @startuml


title Dogu Controller Flow

' Declaring actors and participants
actor "Customer" as client
participant  dogu_controller as controller

' Automatically increments and displays step numbers
autonumber

client -> controller : Reconcile
controller -> usecase : HandleUntilApplied
usecase -> warpMenuEntryStep : run

participant WarpMenuEntryManager as manager

activate manager
warpMenuEntryStep -> manager : EnsureWarpMenuEntry
manager -> doguFetcher : FetchForResource
alt warp tag present
manager -> warpMenuEntryBuilders : buildWarpMenuEntry
activate manager
manager -> wm.client : Get
alt warp menu not found
manager -> wm.client : create
else warp menu is present
manager -> wm.client : Update
end
deactivate manager
else warp tag is not present

manager -> wm.client : Get
alt warp menu present
manager -> wm.client : delete
end
end
deactivate manager


@enduml