Dogu Controller Installation Flow @startuml
title Dogu Controller Installation Flow

root.controller.initfx.controlManager  : warpMenuEntryV1.AddToScheme
root.controller.initfx.interfaces : interfaces for warpmenuentryClient , warpmenuentryInterface
root.controller.initfx.k8s : clients for warpmenuentryClient , warpmenuentryInterface

root.controller.steps.install.interfaces : warpMenuEntryManager
root.controller.steps.usecase.usecase : NewDoguInstallOrChangeUseCase

root.controller.steps.usecase.warpmenuentry.interfaces: new class
root.controller.steps.usecase.warpmenuentry.manager: new class
root.controller.steps.usecase.warpmenuentry.builder:new class

root.main : setup manager, step, client-set/interfaces

root.controller.dogu_controller : owns_WarpMenuEntry


@enduml