Dogu Controller Reconcile Flow For WarpMenuEntry @startuml
!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master

!includeurl CLOUDOGUURL/common.puml
!includeurl CLOUDOGUURL/dogus/cloudogu.puml
!includeurl CLOUDOGUURL/tools/docker.puml
!includeurl CLOUDOGUURL/tools/k8s.puml
!includeurl CLOUDOGUURL/dogus/cas.puml
!includeurl CLOUDOGUURL/dogus/openldap.puml
!includeurl CLOUDOGUURL/dogus/nginx.puml
!includeurl CLOUDOGUURL/dogus/scm.puml
!includeurl CLOUDOGUURL/dogus/redmine.puml
!includeurl CLOUDOGUURL/dogus/postgresql.puml
!define SECONDARY_COLOR #55EE55


title Dogu Controller Reconcile Flow For WarpMenuEntry

' Declaring actors and participants
actor "new/update/delete Dogu " as client
participant  dogu_controller as controller

' Automatically increments and displays step numbers
autonumber

client -> controller : Reconcile
controller -> usecase : HandleUntilApplied
usecase -> warpMenuEntryStep : run

participant WarpMenuEntryManager as manager

activate manager
warpMenuEntryStep -> manager : EnsureWarpMenuEntry
manager -> doguFetcher : FetchForResource
manager -> wm.client : Get
alt warp tag present
    manager -> manager : createNewWarpMenuEntry
    activate manager
    alt warp menu not found
        manager -> wm.client : create
    else warp menu is present
        alt warp menu is not same
            manager -> wm.client : Update
        end
    end
    deactivate manager
else warp tag is not present
    manager -> wm.client : Get
    alt warp menu present
    manager -> wm.client : delete
    end
end
deactivate manager


@enduml