// Code generated by mockery v2.53.5. DO NOT EDIT.

package upgrade

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/apps/v1"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
)

// mockResourceUpserter is an autogenerated mock type for the resourceUpserter type
type mockResourceUpserter struct {
	mock.Mock
}

type mockResourceUpserter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockResourceUpserter) EXPECT() *mockResourceUpserter_Expecter {
	return &mockResourceUpserter_Expecter{mock: &_m.Mock}
}

// UpsertDoguDeployment provides a mock function with given fields: ctx, doguResource, dogu, deploymentPatch
func (_m *mockResourceUpserter) UpsertDoguDeployment(ctx context.Context, doguResource *v2.Dogu, dogu *core.Dogu, deploymentPatch func(*v1.Deployment)) (*v1.Deployment, error) {
	ret := _m.Called(ctx, doguResource, dogu, deploymentPatch)

	if len(ret) == 0 {
		panic("no return value specified for UpsertDoguDeployment")
	}

	var r0 *v1.Deployment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu, *core.Dogu, func(*v1.Deployment)) (*v1.Deployment, error)); ok {
		return rf(ctx, doguResource, dogu, deploymentPatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu, *core.Dogu, func(*v1.Deployment)) *v1.Deployment); ok {
		r0 = rf(ctx, doguResource, dogu, deploymentPatch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Deployment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.Dogu, *core.Dogu, func(*v1.Deployment)) error); ok {
		r1 = rf(ctx, doguResource, dogu, deploymentPatch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockResourceUpserter_UpsertDoguDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertDoguDeployment'
type mockResourceUpserter_UpsertDoguDeployment_Call struct {
	*mock.Call
}

// UpsertDoguDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
//   - dogu *core.Dogu
//   - deploymentPatch func(*v1.Deployment)
func (_e *mockResourceUpserter_Expecter) UpsertDoguDeployment(ctx interface{}, doguResource interface{}, dogu interface{}, deploymentPatch interface{}) *mockResourceUpserter_UpsertDoguDeployment_Call {
	return &mockResourceUpserter_UpsertDoguDeployment_Call{Call: _e.mock.On("UpsertDoguDeployment", ctx, doguResource, dogu, deploymentPatch)}
}

func (_c *mockResourceUpserter_UpsertDoguDeployment_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu, dogu *core.Dogu, deploymentPatch func(*v1.Deployment))) *mockResourceUpserter_UpsertDoguDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu), args[2].(*core.Dogu), args[3].(func(*v1.Deployment)))
	})
	return _c
}

func (_c *mockResourceUpserter_UpsertDoguDeployment_Call) Return(_a0 *v1.Deployment, _a1 error) *mockResourceUpserter_UpsertDoguDeployment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockResourceUpserter_UpsertDoguDeployment_Call) RunAndReturn(run func(context.Context, *v2.Dogu, *core.Dogu, func(*v1.Deployment)) (*v1.Deployment, error)) *mockResourceUpserter_UpsertDoguDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// newMockResourceUpserter creates a new instance of mockResourceUpserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockResourceUpserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockResourceUpserter {
	mock := &mockResourceUpserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
