// Code generated by mockery v2.53.3. DO NOT EDIT.

package upgrade

import (
	context "context"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// mockUpgradeChecker is an autogenerated mock type for the upgradeChecker type
type mockUpgradeChecker struct {
	mock.Mock
}

type mockUpgradeChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUpgradeChecker) EXPECT() *mockUpgradeChecker_Expecter {
	return &mockUpgradeChecker_Expecter{mock: &_m.Mock}
}

// IsUpgrade provides a mock function with given fields: ctx, doguResource
func (_m *mockUpgradeChecker) IsUpgrade(ctx context.Context, doguResource *v2.Dogu) (bool, error) {
	ret := _m.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for IsUpgrade")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) (bool, error)); ok {
		return rf(ctx, doguResource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) bool); ok {
		r0 = rf(ctx, doguResource)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.Dogu) error); ok {
		r1 = rf(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockUpgradeChecker_IsUpgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUpgrade'
type mockUpgradeChecker_IsUpgrade_Call struct {
	*mock.Call
}

// IsUpgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
func (_e *mockUpgradeChecker_Expecter) IsUpgrade(ctx interface{}, doguResource interface{}) *mockUpgradeChecker_IsUpgrade_Call {
	return &mockUpgradeChecker_IsUpgrade_Call{Call: _e.mock.On("IsUpgrade", ctx, doguResource)}
}

func (_c *mockUpgradeChecker_IsUpgrade_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu)) *mockUpgradeChecker_IsUpgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *mockUpgradeChecker_IsUpgrade_Call) Return(_a0 bool, _a1 error) *mockUpgradeChecker_IsUpgrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockUpgradeChecker_IsUpgrade_Call) RunAndReturn(run func(context.Context, *v2.Dogu) (bool, error)) *mockUpgradeChecker_IsUpgrade_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUpgradeChecker creates a new instance of mockUpgradeChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUpgradeChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUpgradeChecker {
	mock := &mockUpgradeChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
