apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-dogu-operator.name" . }}-additional-images
  labels:
    {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
data:
  chownInitImage: {{ .Values.additionalImages.chownInitImage | quote }}
  exporterImage: {{ .Values.additionalImages.exporterImage | quote }}
  additionalMountsInitContainerImage: {{ .Values.additionalImages.additionalMountsInitContainerImage | quote }}
