apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-dogu-operator-additional-images
  labels:
    {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
data:
  chownInitImage: {{ .Values.additionalImages.chownInitImage | quote }}
