# necessary for installing nginx-ingress

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "k8s-dogu-operator.name" . }}-cluster-role'
  labels:
    {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - patch
