apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-dogu-operator.name" . }}-leader-election-rolebinding
  labels:
    {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "k8s-dogu-operator.name" . }}-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "k8s-dogu-operator.name" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
