apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-dogu-operator.name" . }}-manager-dogu-v3-role
  labels:
    {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
rules:
  # dogu v3: create and delete flux resources analogous to the dogu CR
  - apiGroups:
      - "source.toolkit.fluxcd.io"
    resources:
      - helmreleases
      - ocirepositories
    verbs:
      - create
      - list
      - get
      - watch
      - patch
  - apiGroups:
      - "source.toolkit.fluxcd.io"
    resources:
      - helmreleases/status
      - ocirepositories/status
    verbs:
      - get