apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-dogu-operator.name" . }}-manager-config
  labels:
    {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
data:
  network_policies_enabled: "{{- if .Values.global.networkPolicies.enabled }}true{{- else }}false{{- end }}"
