apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-dogu-operator.name" . }}-manager-role
  labels:
    {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - dogus
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - dogus/status
  verbs:
  - get
  - update
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - dogurestarts
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - k8s.cloudogu.com
  resources:
  - dogurestarts/status
  verbs:
  - get
  - update
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - watch
    - create
    - update
    - delete
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - get
    - update
    - delete
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - create
    - update
    - delete
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - get
    - update
    - delete
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
    - create
    - get
    - update
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - create
    - delete
- apiGroups:
    - ""
  resources:
    - pods/exec
  verbs:
    - create
- apiGroups:
    - ""
  resources: # necessary for installing nginx-ingress
    - roles
    - rolebindings
    - serviceaccounts
  verbs:
    - patch
