apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-dogu-operator.name" . }}-metrics-service
  labels:
    control-plane: controller-manager
    {{- include "k8s-dogu-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
