{{- if and
        .Values.reloader.enabled
        .Values.global.networkPolicies.enabled
        (or .Values.reloader.reloader.podMonitor.enabled .Values.reloader.reloader.serviceMonitor.enabled)
}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
{{ include "reloader-helm3.annotations" . | indent 4 }}
  labels:
{{ include "k8s-dogu-operator.labels" . | nindent 4 }}
{{- if .Values.reloader.reloader.matchLabels }}
{{ tpl (toYaml .Values.reloader.reloader.matchLabels) . | indent 4 }}
{{- end }}
  name: {{ include "k8s-dogu-operator.name" . }}-reloader
  namespace: {{ .Values.reloader.namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "k8s-dogu-operator.name" . }}-reloader
      release: {{ .Release.Name | quote }}
{{- if .Values.reloader.reloader.matchLabels }}
{{ tpl (toYaml .Values.reloader.reloader.matchLabels) . | indent 6 }}
{{- end }}
  policyTypes:
  - Ingress
  ingress:
    - ports:
        - port: http
      {{- with .Values.reloader.reloader.netpol.from}}
      from:
        {{- toYaml .| nindent 8 }}
      {{- end }}
{{- end }}
