// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package charts

import (
	"context"

	"github.com/cloudogu/k8s-dogu-lib/v3/api/v3beta1"
	mock "github.com/stretchr/testify/mock"
	"helm.sh/helm/v3/pkg/chart"
)

// NewMockChartProvider creates a new instance of MockChartProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChartProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChartProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockChartProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockChartProvider is an autogenerated mock type for the ChartProvider type
type MockChartProvider struct {
	mock.Mock
}

type MockChartProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChartProvider) EXPECT() *MockChartProvider_Expecter {
	return &MockChartProvider_Expecter{mock: &_m.Mock}
}

// GetChart provides a mock function for the type MockChartProvider
func (_mock *MockChartProvider) GetChart(ctx context.Context, doguResource *v3beta1.Dogu) (*chart.Chart, error) {
	ret := _mock.Called(ctx, doguResource)

	if len(ret) == 0 {
		panic("no return value specified for GetChart")
	}

	var r0 *chart.Chart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu) (*chart.Chart, error)); ok {
		return returnFunc(ctx, doguResource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v3beta1.Dogu) *chart.Chart); ok {
		r0 = returnFunc(ctx, doguResource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chart.Chart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v3beta1.Dogu) error); ok {
		r1 = returnFunc(ctx, doguResource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChartProvider_GetChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChart'
type MockChartProvider_GetChart_Call struct {
	*mock.Call
}

// GetChart is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v3beta1.Dogu
func (_e *MockChartProvider_Expecter) GetChart(ctx any, doguResource any) *MockChartProvider_GetChart_Call {
	return &MockChartProvider_GetChart_Call{Call: _e.mock.On("GetChart", ctx, doguResource)}
}

func (_c *MockChartProvider_GetChart_Call) Run(run func(ctx context.Context, doguResource *v3beta1.Dogu)) *MockChartProvider_GetChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v3beta1.Dogu
		if args[1] != nil {
			arg1 = args[1].(*v3beta1.Dogu)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChartProvider_GetChart_Call) Return(chart1 *chart.Chart, err error) *MockChartProvider_GetChart_Call {
	_c.Call.Return(chart1, err)
	return _c
}

func (_c *MockChartProvider_GetChart_Call) RunAndReturn(run func(ctx context.Context, doguResource *v3beta1.Dogu) (*chart.Chart, error)) *MockChartProvider_GetChart_Call {
	_c.Call.Return(run)
	return _c
}
