// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package charts

import (
	"context"
	"sync"

	"github.com/cloudogu/k8s-dogu-lib/v3/api/v3beta1"
)

// Ensure that mockChartLoader does implement ChartProvider.
// If this is not the case, regenerate this file with mockery.
var _ ChartProvider = &mockChartLoader{}

// mockChartLoader is a mock implementation of ChartProvider.
type mockChartLoader struct {
	// ArtifactDigestFunc mocks the ArtifactDigest method.
	ArtifactDigestFunc func(ctx context.Context, doguResource *v3beta1.Dogu) (string, error)

	// GetChartArchiveFunc mocks the GetChartArchive method.
	GetChartArchiveFunc func(ctx context.Context, doguResource *v3beta1.Dogu) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// ArtifactDigest holds details about calls to the ArtifactDigest method.
		ArtifactDigest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DoguResource is the doguResource argument value.
			DoguResource *v3beta1.Dogu
		}
		// GetChartArchive holds details about calls to the GetChartArchive method.
		GetChartArchive []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DoguResource is the doguResource argument value.
			DoguResource *v3beta1.Dogu
		}
	}
	lockArtifactDigest  sync.RWMutex
	lockGetChartArchive sync.RWMutex
}

// ArtifactDigest calls ArtifactDigestFunc.
func (mock *mockChartLoader) ArtifactDigest(ctx context.Context, doguResource *v3beta1.Dogu) (string, error) {
	if mock.ArtifactDigestFunc == nil {
		panic("mockChartLoader.ArtifactDigestFunc: method is nil but ChartProvider.ArtifactDigest was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DoguResource *v3beta1.Dogu
	}{
		Ctx:          ctx,
		DoguResource: doguResource,
	}
	mock.lockArtifactDigest.Lock()
	mock.calls.ArtifactDigest = append(mock.calls.ArtifactDigest, callInfo)
	mock.lockArtifactDigest.Unlock()
	return mock.ArtifactDigestFunc(ctx, doguResource)
}

// ArtifactDigestCalls gets all the calls that were made to ArtifactDigest.
func (mock *mockChartLoader) ArtifactDigestCalls() []struct {
	Ctx          context.Context
	DoguResource *v3beta1.Dogu
} {
	var calls []struct {
		Ctx          context.Context
		DoguResource *v3beta1.Dogu
	}
	mock.lockArtifactDigest.RLock()
	calls = mock.calls.ArtifactDigest
	mock.lockArtifactDigest.RUnlock()
	return calls
}

// GetChartArchive calls GetChartArchiveFunc.
func (mock *mockChartLoader) GetChartArchive(ctx context.Context, doguResource *v3beta1.Dogu) ([]byte, error) {
	if mock.GetChartArchiveFunc == nil {
		panic("mockChartLoader.GetChartArchiveFunc: method is nil but ChartProvider.GetChartArchive was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DoguResource *v3beta1.Dogu
	}{
		Ctx:          ctx,
		DoguResource: doguResource,
	}
	mock.lockGetChartArchive.Lock()
	mock.calls.GetChartArchive = append(mock.calls.GetChartArchive, callInfo)
	mock.lockGetChartArchive.Unlock()
	return mock.GetChartArchiveFunc(ctx, doguResource)
}

// GetChartArchiveCalls gets all the calls that were made to GetChartArchive.
func (mock *mockChartLoader) GetChartArchiveCalls() []struct {
	Ctx          context.Context
	DoguResource *v3beta1.Dogu
} {
	var calls []struct {
		Ctx          context.Context
		DoguResource *v3beta1.Dogu
	}
	mock.lockGetChartArchive.RLock()
	calls = mock.calls.GetChartArchive
	mock.lockGetChartArchive.RUnlock()
	return calls
}
