// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/cloudogu/cesapp/v4/core"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/cloudogu/k8s-dogu-operator/api/v1"
)

// ServiceAccountCreator is an autogenerated mock type for the ServiceAccountCreator type
type ServiceAccountCreator struct {
	mock.Mock
}

// CreateServiceAccounts provides a mock function with given fields: ctx, doguResource, dogu
func (_m *ServiceAccountCreator) CreateServiceAccounts(ctx context.Context, doguResource *v1.Dogu, dogu *core.Dogu) error {
	ret := _m.Called(ctx, doguResource, dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Dogu, *core.Dogu) error); ok {
		r0 = rf(ctx, doguResource, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
