// Code generated by mockery v2.53.5. DO NOT EDIT.

package install

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
)

// mockConditionUpdater is an autogenerated mock type for the conditionUpdater type
type mockConditionUpdater struct {
	mock.Mock
}

type mockConditionUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConditionUpdater) EXPECT() *mockConditionUpdater_Expecter {
	return &mockConditionUpdater_Expecter{mock: &_m.Mock}
}

// UpdateCondition provides a mock function with given fields: ctx, doguResource, condition
func (_m *mockConditionUpdater) UpdateCondition(ctx context.Context, doguResource *v2.Dogu, condition v1.Condition) error {
	ret := _m.Called(ctx, doguResource, condition)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCondition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu, v1.Condition) error); ok {
		r0 = rf(ctx, doguResource, condition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockConditionUpdater_UpdateCondition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCondition'
type mockConditionUpdater_UpdateCondition_Call struct {
	*mock.Call
}

// UpdateCondition is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
//   - condition v1.Condition
func (_e *mockConditionUpdater_Expecter) UpdateCondition(ctx interface{}, doguResource interface{}, condition interface{}) *mockConditionUpdater_UpdateCondition_Call {
	return &mockConditionUpdater_UpdateCondition_Call{Call: _e.mock.On("UpdateCondition", ctx, doguResource, condition)}
}

func (_c *mockConditionUpdater_UpdateCondition_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu, condition v1.Condition)) *mockConditionUpdater_UpdateCondition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu), args[2].(v1.Condition))
	})
	return _c
}

func (_c *mockConditionUpdater_UpdateCondition_Call) Return(_a0 error) *mockConditionUpdater_UpdateCondition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConditionUpdater_UpdateCondition_Call) RunAndReturn(run func(context.Context, *v2.Dogu, v1.Condition) error) *mockConditionUpdater_UpdateCondition_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConditions provides a mock function with given fields: ctx, doguResource, conditions
func (_m *mockConditionUpdater) UpdateConditions(ctx context.Context, doguResource *v2.Dogu, conditions []v1.Condition) error {
	ret := _m.Called(ctx, doguResource, conditions)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConditions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu, []v1.Condition) error); ok {
		r0 = rf(ctx, doguResource, conditions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockConditionUpdater_UpdateConditions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConditions'
type mockConditionUpdater_UpdateConditions_Call struct {
	*mock.Call
}

// UpdateConditions is a helper method to define mock.On call
//   - ctx context.Context
//   - doguResource *v2.Dogu
//   - conditions []v1.Condition
func (_e *mockConditionUpdater_Expecter) UpdateConditions(ctx interface{}, doguResource interface{}, conditions interface{}) *mockConditionUpdater_UpdateConditions_Call {
	return &mockConditionUpdater_UpdateConditions_Call{Call: _e.mock.On("UpdateConditions", ctx, doguResource, conditions)}
}

func (_c *mockConditionUpdater_UpdateConditions_Call) Run(run func(ctx context.Context, doguResource *v2.Dogu, conditions []v1.Condition)) *mockConditionUpdater_UpdateConditions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu), args[2].([]v1.Condition))
	})
	return _c
}

func (_c *mockConditionUpdater_UpdateConditions_Call) Return(_a0 error) *mockConditionUpdater_UpdateConditions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConditionUpdater_UpdateConditions_Call) RunAndReturn(run func(context.Context, *v2.Dogu, []v1.Condition) error) *mockConditionUpdater_UpdateConditions_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConditionUpdater creates a new instance of mockConditionUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConditionUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConditionUpdater {
	mock := &mockConditionUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
