// Code generated by mockery v2.53.3. DO NOT EDIT.

package install

import (
	context "context"

	steps "github.com/cloudogu/k8s-dogu-operator/v3/controllers/steps"
	mock "github.com/stretchr/testify/mock"

	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
)

// MockCreateSensitiveDoguConfigStep is an autogenerated mock type for the CreateSensitiveDoguConfigStep type
type MockCreateSensitiveDoguConfigStep struct {
	mock.Mock
}

type MockCreateSensitiveDoguConfigStep_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateSensitiveDoguConfigStep) EXPECT() *MockCreateSensitiveDoguConfigStep_Expecter {
	return &MockCreateSensitiveDoguConfigStep_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, resource
func (_m *MockCreateSensitiveDoguConfigStep) Run(ctx context.Context, resource *v2.Dogu) steps.StepResult {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 steps.StepResult
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu) steps.StepResult); ok {
		r0 = rf(ctx, resource)
	} else {
		r0 = ret.Get(0).(steps.StepResult)
	}

	return r0
}

// MockCreateSensitiveDoguConfigStep_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCreateSensitiveDoguConfigStep_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - resource *v2.Dogu
func (_e *MockCreateSensitiveDoguConfigStep_Expecter) Run(ctx interface{}, resource interface{}) *MockCreateSensitiveDoguConfigStep_Run_Call {
	return &MockCreateSensitiveDoguConfigStep_Run_Call{Call: _e.mock.On("Run", ctx, resource)}
}

func (_c *MockCreateSensitiveDoguConfigStep_Run_Call) Run(run func(ctx context.Context, resource *v2.Dogu)) *MockCreateSensitiveDoguConfigStep_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu))
	})
	return _c
}

func (_c *MockCreateSensitiveDoguConfigStep_Run_Call) Return(_a0 steps.StepResult) *MockCreateSensitiveDoguConfigStep_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCreateSensitiveDoguConfigStep_Run_Call) RunAndReturn(run func(context.Context, *v2.Dogu) steps.StepResult) *MockCreateSensitiveDoguConfigStep_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateSensitiveDoguConfigStep creates a new instance of MockCreateSensitiveDoguConfigStep. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateSensitiveDoguConfigStep(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateSensitiveDoguConfigStep {
	mock := &MockCreateSensitiveDoguConfigStep{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
